import {Engine,Scene,HemisphericLight,DirectionalLight,Vector3,Color3} from '@babylonjs/core';
import {CLASSES,RARITY,WEAPONS,ENEMIES,BOSSES} from '../data.js';
import {EventBus} from './EventBus.js';
import {InputSystem} from '../systems/InputSystem.js';
import {CameraSystem} from '../systems/CameraSystem.js';
import {CombatSystem} from '../systems/CombatSystem.js';
import {AISystem} from '../systems/AISystem.js';
import {EntityFactory} from '../entities/EntityFactory.js';
import {WorldManager} from '../world/WorldManager.js';
import {HUD} from '../ui/HUD.js';

const map=Object.fromEntries(WEAPONS.map(w=>[w.id,w]));
export class Game{
  constructor(canvas,hudRoot,modal){this.canvas=canvas;this.hudRoot=hudRoot;this.modal=modal;this.engine=new Engine(canvas,true,{preserveDrawingBuffer:false,stencil:false,adaptToDeviceRatio:true});this.scene=new Scene(this.engine);this.scene.clearColor=Color3.FromHexString('#0d1117').toColor4(1);this.bus=new EventBus();this.input=new InputSystem(canvas);this.input.start();this.factory=new EntityFactory(this.scene);this.world=new WorldManager(this.scene);this.camera=new CameraSystem(this.scene,this.input);this.combat=new CombatSystem(this.scene,this.factory,this.bus,this.camera);this.ai=new AISystem();this.hud=new HUD(hudRoot);this.player=null;this.enemies=[];this.pickups=[];this.room=0;this.floor=1;this.roomInFloor=0;this.reloading=false;this.reloadT=0;this.ammo=0;this.weapon=null;this.combo=0;this.comboT=0;this.kills=0;this.initialEnemyCount=0;this.reinforcementTriggered=false;this.roomTransitionT=0;this.lastSlot=-1;this.bindEvents();this.setupScene()}
  setupScene(){new HemisphericLight('hemi',new Vector3(0,1,0),this.scene).intensity=1.3;const sun=new DirectionalLight('sun',new Vector3(-.4,-1,.35),this.scene);sun.position=new Vector3(35,55,-25);sun.intensity=2;this.scene.collisionsEnabled=true;window.addEventListener('resize',()=>this.engine.resize())}
  bindEvents(){
    this.bus.on('enemy:killed',e=>{this.kills++;this.combo++;this.comboT=3.2;const missing=this.player?1-this.player.hp/this.player.maxHp:0,chance=(e.boss?1:.1+missing*.34+(e.elite?.2:0));if(Math.random()<chance)this.spawnHealth(e.node.position,e.boss?42:e.elite?32:null)});
    this.bus.on('enemy:hit',({enemy})=>{for(const ally of this.enemies)if(!ally.dead&&Vector3.DistanceSquared(ally.node.position,enemy.node.position)<28*28){ally.alerted=true;ally.lastSeen=performance.now()/1000}});
    this.bus.on('player:dead',()=>this.gameOver());window.addEventListener('keydown',e=>{if(e.code==='KeyR')this.reload()})
  }
  chooseClass(){this.modal.classList.add('show');this.modal.innerHTML=`<div class="card hero"><div class="eyebrow">OPERATIVE SELECT</div><h1>Class seç</h1><div class="grid">${Object.entries(CLASSES).map(([id,c])=>`<button class="choice" data-class="${id}"><h3>${c.name}</h3><p>${c.desc.replace(/aim assist/gi,'precision')}</p><small>HP ${c.hp} · SPD ${c.speed}</small></button>`).join('')}</div></div>`;this.modal.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>this.start(b.dataset.class))}
  start(id){const c=CLASSES[id];this.modal.classList.remove('show');const node=this.factory.createPlayer(c);this.player={node,hp:c.hp,maxHp:c.hp,speed:c.speed,damage:c.damage,melee:c.melee||1,attackSpeed:1,crit:c.crit||.08,coins:0,ifr:0,dashCd:0,dashT:0};this.slots=c.slots.map(id=>map[id]);this.slot=0;this.weapon=this.slots[0];this.ammo=this.weapon.mag||0;this.buildRoom();this.engine.runRenderLoop(()=>this.frame())}
  buildRoom(){for(const e of this.enemies)e.node.dispose();for(const p of this.pickups)p.node.dispose();this.enemies=[];this.pickups=[];this.combat.clear();this.floor=Math.floor(this.room/12)+1;this.roomInFloor=this.room%12;this.kills=0;this.combo=0;this.reinforcementTriggered=false;this.roomTransitionT=0;const info=this.world.build(this.room,this.floor);this.player.node.position.copyFrom(info.spawn);const boss=this.roomInFloor===11;if(boss){const def=BOSSES[(this.floor-1)%BOSSES.length];this.spawnEnemy({...def,speed:2.8,r:1.8,damage:46,xp:300,ai:'boss'},true,new Vector3(0,0,-this.world.bounds+28));this.initialEnemyCount=1}else{const count=Math.min(34,15+Math.floor(this.roomInFloor*1.1)+this.floor*2),squads=Math.max(3,Math.ceil(count/6));let spawned=0;for(let s=0;s<squads;s++){const center=this.safeSpawnCenter();const group=Math.min(count-spawned,4+Math.floor(Math.random()*4));for(let i=0;i<group;i++){if(spawned>=count)break;const offset=new Vector3((Math.random()-.5)*13,0,(Math.random()-.5)*13);this.spawnEnemy(ENEMIES[(Math.random()*ENEMIES.length)|0],false,center.add(offset));spawned++}}this.initialEnemyCount=this.enemies.length}}
  safeSpawnCenter(){const b=this.world.bounds-24;for(let i=0;i<40;i++){const p=new Vector3((Math.random()*2-1)*b,0,(Math.random()*2-1)*b);if(!this.world.blocked(p,4)&&Vector3.DistanceSquared(p,this.player.node.position)>42*42)return p}return new Vector3(0,0,-b*.45)}
  spawnEnemy(def,boss=false,pos=null){const node=this.factory.createEnemy(def,boss),elite=!boss&&Math.random()<Math.min(.22,.08+this.floor*.012);const b=this.world.bounds-10;let p=pos||new Vector3((Math.random()*2-1)*b,0,(Math.random()*2-1)*(b*.8));for(let i=0;i<20&&this.world.blocked(p,def.r||.8);i++)p=new Vector3((Math.random()*2-1)*b,0,(Math.random()*2-1)*b);node.position.copyFrom(p);if(elite)node.scaling.scaleInPlace(1.17);const baseHp=(def.hp||100)*(1+this.floor*.28)*(elite?1.75:1);this.enemies.push({node,def,boss,elite,hp:baseHp,maxHp:baseHp,speed:(def.speed||3)*(1+Math.min(.38,this.floor*.025))*(elite?1.08:1),radius:(def.r||.8)*(elite?1.12:1),dead:false,damage:(def.damage||24)*(elite?1.28:1),phase:Math.random()*6.28,alerted:boss,awareness:boss?110:undefined})}
  spawnHealth(pos,heal=null){const node=this.factory.createHealthPickup();node.position.copyFrom(pos).add(new Vector3(0,.45,0));this.pickups.push({node,heal:heal||22+Math.round(Math.random()*16),dead:false,type:'health'})}
  spawnReinforcements(){this.reinforcementTriggered=true;const amount=Math.min(9,4+this.floor);for(let i=0;i<amount;i++){const center=this.safeSpawnCenter();this.spawnEnemy(ENEMIES[(Math.random()*ENEMIES.length)|0],false,center.add(new Vector3((Math.random()-.5)*9,0,(Math.random()-.5)*9)))}this.initialEnemyCount+=amount}
  updatePlayer(dt){this.player.dashCd=Math.max(0,this.player.dashCd-dt);this.player.dashT=Math.max(0,this.player.dashT-dt);const f=this.camera.forward(),r=new Vector3(-f.z,0,f.x),dir=Vector3.Zero();if(this.input.down('KeyW'))dir.addInPlace(f);if(this.input.down('KeyS'))dir.subtractInPlace(f);if(this.input.down('KeyD'))dir.addInPlace(r);if(this.input.down('KeyA'))dir.subtractInPlace(r);if(dir.lengthSquared()>0){dir.normalize();if(this.input.down('ShiftLeft')&&this.player.dashCd<=0){this.player.dashCd=.85;this.player.dashT=.14;this.player.ifr=Math.max(this.player.ifr,.16);this.camera.kick(.05)}const mul=this.player.dashT>0?3.1:1;const candidate=this.player.node.position.add(dir.scale(this.player.speed*dt*mul));if(!this.world.blocked(candidate,.72))this.player.node.position.copyFrom(candidate);this.player.node.rotation.y=Math.atan2(dir.x,dir.z)}this.world.clamp(this.player.node.position,.8);if(this.input.mouse.right&&this.camera.locked)this.player.node.rotation.y=this.camera.yaw}
  updateSlots(){let next=-1;if(this.input.down('Digit1'))next=0;if(this.input.down('Digit2'))next=1;if(this.input.down('Digit3'))next=2;if(next>=0&&next!==this.lastSlot&&this.slots[next]){this.slot=next;this.weapon=this.slots[next];this.ammo=this.weapon.mag||0;this.reloading=false}this.lastSlot=next}
  reload(){if(!this.weapon||this.weapon.kind==='melee'||this.reloading||this.ammo>=this.weapon.mag)return;this.reloading=true;this.reloadT=this.weapon.reload||1;this.bus.emit('weapon:reload',{weapon:this.weapon})}
  updateReload(dt){if(!this.reloading)return;this.reloadT-=dt;if(this.reloadT<=0){this.reloading=false;this.ammo=this.weapon.mag||0}}
  updatePickups(dt){for(const p of this.pickups){if(p.dead)continue;p.node.rotation.y+=dt*2.5;const d=Vector3.Distance(p.node.position,this.player.node.position);if(d<8)p.node.position=Vector3.Lerp(p.node.position,this.player.node.position.add(new Vector3(0,.5,0)),dt*3.5);if(d<1){if(p.type==='health')this.player.hp=Math.min(this.player.maxHp,this.player.hp+p.heal);p.dead=true;p.node.dispose()}}this.pickups=this.pickups.filter(p=>!p.dead)}
  gameOver(){if(this.modal.classList.contains('show'))return;document.exitPointerLock?.();this.modal.classList.add('show');this.modal.innerHTML=`<div class="card death"><div class="eyebrow">RUN ENDED</div><h1>YOU DIED</h1><p>Deck ${this.floor}, room ${this.roomInFloor+1}. ${this.kills} kill.</p><button class="choice" id="restart"><h3>Restart run</h3></button></div>`;this.modal.querySelector('#restart').onclick=()=>location.reload()}
  frame(){if(!this.player||this.modal.classList.contains('show')){this.scene.render();return}const dt=Math.min(.033,this.engine.getDeltaTime()/1000);this.comboT=Math.max(0,this.comboT-dt);if(this.comboT<=0)this.combo=0;this.updateSlots();this.updateReload(dt);this.updatePlayer(dt);const state={player:this.player,input:this.input,camera:this.camera,world:this.world,bus:this.bus,enemies:this.enemies,weapon:this.weapon,ammo:this.ammo,reloading:this.reloading,rarityColor:r=>RARITY[r]?.color||'#ffffff'};this.combat.update(dt,state);this.ammo=state.ammo;this.ai.update(dt,state);this.camera.update(dt,this.player,this.enemies);this.updatePickups(dt);const alive=this.enemies.filter(e=>!e.dead).length;if(!this.reinforcementTriggered&&this.roomInFloor!==11&&this.initialEnemyCount>=10&&alive>0&&alive<=Math.ceil(this.initialEnemyCount*.32))this.spawnReinforcements();if(this.enemies.length&&alive===0){this.roomTransitionT+=dt;if(this.roomTransitionT>1.1){this.room++;this.player.hp=Math.min(this.player.maxHp,this.player.hp+this.player.maxHp*.08);this.buildRoom()}}else this.roomTransitionT=0;this.hud.render({...this,player:this.player,input:this.input,camera:this.camera,weapon:this.weapon,ammo:this.ammo,reloading:this.reloading,alive,combo:this.combo});this.scene.render()}
}
