import {Engine,Scene,HemisphericLight,DirectionalLight,Vector3,Color3} from '@babylonjs/core';
import {CLASSES,RARITY,WEAPONS,ENEMIES,BOSSES} from '../data.js';
import {EventBus} from './EventBus.js';
import {InputSystem} from '../systems/InputSystem.js';
import {CameraSystem} from '../systems/CameraSystem.js';
import {CombatSystem} from '../systems/CombatSystem.js';
import {AISystem} from '../systems/AISystem.js';
import {EntityFactory} from '../entities/EntityFactory.js';
import {WorldManager} from '../world/WorldManager.js';
import {HUD} from '../ui/HUD.js';

const map=Object.fromEntries(WEAPONS.map(w=>[w.id,w]));
export class Game{
  constructor(canvas,hudRoot,modal){this.canvas=canvas;this.hudRoot=hudRoot;this.modal=modal;this.engine=new Engine(canvas,true,{preserveDrawingBuffer:false,stencil:false,adaptToDeviceRatio:true});this.scene=new Scene(this.engine);this.scene.clearColor=Color3.FromHexString('#0d1117').toColor4(1);this.bus=new EventBus();this.input=new InputSystem(canvas);this.input.start();this.factory=new EntityFactory(this.scene);this.world=new WorldManager(this.scene);this.camera=new CameraSystem(this.scene,this.input);this.combat=new CombatSystem(this.scene,this.factory,this.bus,this.camera);this.ai=new AISystem();this.hud=new HUD(hudRoot);this.player=null;this.enemies=[];this.pickups=[];this.room=0;this.floor=1;this.roomInFloor=0;this.reloading=false;this.reloadT=0;this.ammo=0;this.weapon=null;this.bindEvents();this.setupScene()}
  setupScene(){new HemisphericLight('hemi',new Vector3(0,1,0),this.scene).intensity=1.25;const sun=new DirectionalLight('sun',new Vector3(-.4,-1,.35),this.scene);sun.position=new Vector3(20,35,-10);sun.intensity=2.1;this.scene.collisionsEnabled=true;window.addEventListener('resize',()=>this.engine.resize())}
  bindEvents(){this.bus.on('enemy:killed',e=>{if(Math.random()<.18||e.boss)this.spawnHealth(e.node.position)});this.bus.on('weapon:fired',()=>{});window.addEventListener('keydown',e=>{if(e.code==='KeyR')this.reload()})}
  chooseClass(){this.modal.classList.add('show');this.modal.innerHTML=`<div class="card hero"><div class="eyebrow">OPERATIVE SELECT</div><h1>Class seç</h1><div class="grid">${Object.entries(CLASSES).map(([id,c])=>`<button class="choice" data-class="${id}"><h3>${c.name}</h3><p>${c.desc.replace(/aim assist/gi,'precision')}</p><small>HP ${c.hp} · SPD ${c.speed}</small></button>`).join('')}</div></div>`;this.modal.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>this.start(b.dataset.class))}
  start(id){const c=CLASSES[id];this.modal.classList.remove('show');const node=this.factory.createPlayer(c.color);this.player={node,hp:c.hp,maxHp:c.hp,speed:c.speed,damage:c.damage,melee:c.melee||1,attackSpeed:1,coins:0};this.slots=c.slots.map(id=>map[id]);this.slot=0;this.weapon=this.slots[0];this.ammo=this.weapon.mag||0;this.buildRoom();this.engine.runRenderLoop(()=>this.frame())}
  buildRoom(){for(const e of this.enemies)e.node.dispose();for(const p of this.pickups)p.node.dispose();this.enemies=[];this.pickups=[];this.combat.clear();this.floor=Math.floor(this.room/12)+1;this.roomInFloor=this.room%12;const info=this.world.build(this.room,this.floor);this.player.node.position.copyFrom(info.spawn);const boss=this.roomInFloor===11;if(boss){const def=BOSSES[(this.floor-1)%BOSSES.length];this.spawnEnemy({...def,speed:2.6,r:1.6,damage:42,xp:300},true)}else{const count=Math.min(18,7+Math.floor(this.roomInFloor*.6)+this.floor);for(let i=0;i<count;i++)this.spawnEnemy(ENEMIES[(Math.random()*ENEMIES.length)|0],false)}}
  spawnEnemy(def,boss){const node=this.factory.createEnemy(def,boss);const b=this.world.bounds-8;node.position.set((Math.random()*2-1)*b,0,(Math.random()*2-1)*(b*.72));this.enemies.push({node,def,boss,hp:(def.hp||100)*(1+this.floor*.28),maxHp:def.hp||100,speed:(def.speed||3)*(1+Math.min(.35,this.floor*.025)),radius:def.r||.8,dead:false,damage:def.damage||24})}
  spawnHealth(pos){const node=this.factory.createHealthPickup();node.position.copyFrom(pos).add(new Vector3(0,.45,0));this.pickups.push({node,heal:22+Math.round(Math.random()*16),dead:false})}
  updatePlayer(dt){const f=this.camera.forward(),r=new Vector3(-f.z,0,f.x),dir=Vector3.Zero();if(this.input.down('KeyW'))dir.addInPlace(f);if(this.input.down('KeyS'))dir.subtractInPlace(f);if(this.input.down('KeyD'))dir.addInPlace(r);if(this.input.down('KeyA'))dir.subtractInPlace(r);if(dir.lengthSquared()>0){dir.normalize();this.player.node.position.addInPlace(dir.scale(this.player.speed*dt));this.player.node.rotation.y=Math.atan2(dir.x,dir.z)}this.world.clamp(this.player.node.position,.8);if(this.input.mouse.right&&this.camera.locked)this.player.node.rotation.y=this.camera.yaw}
  reload(){if(!this.weapon||this.weapon.kind==='melee'||this.reloading||this.ammo>=this.weapon.mag)return;this.reloading=true;this.reloadT=this.weapon.reload||1;this.bus.emit('weapon:reload',{weapon:this.weapon})}
  updateReload(dt){if(!this.reloading)return;this.reloadT-=dt;if(this.reloadT<=0){this.reloading=false;this.ammo=this.weapon.mag||0}}
  updatePickups(dt){for(const p of this.pickups){if(p.dead)continue;p.node.rotation.y+=dt*2.5;const d=Vector3.Distance(p.node.position,this.player.node.position);if(d<6)p.node.position=Vector3.Lerp(p.node.position,this.player.node.position.add(new Vector3(0,.5,0)),dt*3);if(d<1){this.player.hp=Math.min(this.player.maxHp,this.player.hp+p.heal);p.dead=true;p.node.dispose()}}this.pickups=this.pickups.filter(p=>!p.dead)}
  frame(){if(!this.player||this.modal.classList.contains('show')){this.scene.render();return}const dt=Math.min(.033,this.engine.getDeltaTime()/1000);this.updateReload(dt);this.updatePlayer(dt);const state={player:this.player,input:this.input,camera:this.camera,world:this.world,bus:this.bus,enemies:this.enemies,weapon:this.weapon,ammo:this.ammo,reloading:this.reloading,rarityColor:r=>RARITY[r]?.color||'#ffffff'};this.combat.update(dt,state);this.ammo=state.ammo;this.ai.update(dt,state);this.camera.update(dt,this.player,this.enemies);this.updatePickups(dt);if(this.enemies.length&&this.enemies.every(e=>e.dead)){this.room++;this.buildRoom()}this.hud.render({...this,player:this.player,input:this.input,camera:this.camera,weapon:this.weapon,ammo:this.ammo,reloading:this.reloading});this.scene.render()}
}
