import {Vector3,Color3} from '@babylonjs/core';

export class CombatSystem{
  constructor(scene,factory,bus,camera){this.scene=scene;this.factory=factory;this.bus=bus;this.camera=camera;this.projectiles=[];this.cooldown=0}
  update(dt,state){this.cooldown=Math.max(0,this.cooldown-dt);if(state.input.mouse.left)this.tryFire(state);for(const p of this.projectiles){p.life-=dt;p.node.position.addInPlace(p.velocity.scale(dt));for(const e of state.enemies){if(e.dead)continue;if(Vector3.DistanceSquared(p.node.position,e.node.position)<(e.radius+.35)**2){e.hp-=p.damage;p.life=0;this.bus.emit('enemy:hit',{enemy:e,damage:p.damage});this.camera.kick(.06);if(e.hp<=0){e.dead=true;e.node.setEnabled(false);this.bus.emit('enemy:killed',e)}break}}}this.projectiles=this.projectiles.filter(p=>{if(p.life>0)return true;p.node.dispose();return false})}
  tryFire(state){const w=state.weapon;if(!w||this.cooldown>0||state.reloading)return;if(w.kind==='melee'){this.cooldown=1/(w.rate*state.player.attackSpeed);this.melee(state,w);return}if(state.ammo<=0){this.bus.emit('weapon:empty');return}this.cooldown=1/(w.rate*state.player.attackSpeed);state.ammo--;this.bus.emit('weapon:fired',{weapon:w,ammo:state.ammo});const dir=this.camera.locked&&state.input.mouse.right?this.camera.locked.node.position.add(new Vector3(0,1,0)).subtract(state.player.node.position.add(new Vector3(0,1.15,0))).normalize():this.camera.camera.getForwardRay().direction.normalize();const origin=state.player.node.position.add(new Vector3(.45,1.15,0)).add(dir.scale(.7));for(let i=0;i<(w.pellets||1);i++){const d=dir.clone();if(w.spread){d.x+=(Math.random()-.5)*w.spread;d.y+=(Math.random()-.5)*w.spread*.3;d.z+=(Math.random()-.5)*w.spread;d.normalize()}const node=this.factory.createProjectile(state.rarityColor(w.rarity),w.kind==='grenade'?.16:.09);node.position.copyFrom(origin);this.projectiles.push({node,velocity:d.scale(w.speed),damage:w.damage*state.player.damage,life:(w.range||60)/w.speed,w})}this.camera.kick(.035)}
  melee(state,w){const f=this.camera.forward();let hit=false;for(const e of state.enemies){if(e.dead)continue;const v=e.node.position.subtract(state.player.node.position);const dist=v.length();v.y=0;if(dist<(w.range||3.2)+e.radius&&Vector3.Dot(v.normalize(),f)>.2){e.hp-=w.damage*state.player.damage*state.player.melee;hit=true;this.bus.emit('enemy:hit',{enemy:e,damage:w.damage});if(e.hp<=0){e.dead=true;e.node.setEnabled(false);this.bus.emit('enemy:killed',e)}}}this.bus.emit('weapon:melee',{hit});if(hit)this.camera.kick(.12)}
  clear(){for(const p of this.projectiles)p.node.dispose();this.projectiles=[]}
}
