import {Vector3,Color3} from '@babylonjs/core';

export class CombatSystem{
  constructor(scene,factory,bus,camera){this.scene=scene;this.factory=factory;this.bus=bus;this.camera=camera;this.projectiles=[];this.enemyProjectiles=[];this.cooldown=0;this.pendingEnemyShots=[];this.bus.on('enemy:fire',shot=>this.pendingEnemyShots.push(shot))}
  update(dt,state){
    this.cooldown=Math.max(0,this.cooldown-dt);state.player.ifr=Math.max(0,(state.player.ifr||0)-dt);if(state.input.mouse.left)this.tryFire(state);
    while(this.pendingEnemyShots.length)this.spawnEnemyShot(this.pendingEnemyShots.shift());
    for(const p of this.projectiles){p.life-=dt;p.node.position.addInPlace(p.velocity.scale(dt));if(state.world.blocked(p.node.position,.08)){p.life=0;continue}for(const e of state.enemies){if(e.dead)continue;if(Vector3.DistanceSquared(p.node.position,e.node.position.add(new Vector3(0,1,0)))<(e.radius+.42)**2){const crit=Math.random()<(state.player.crit||0),damage=p.damage*(crit?1.75:1);this.damageEnemy(e,damage,crit);p.life=0;break}}}
    for(const p of this.enemyProjectiles){p.life-=dt;p.node.position.addInPlace(p.velocity.scale(dt));if(state.world.blocked(p.node.position,.08)){p.life=0;continue}if(Vector3.DistanceSquared(p.node.position,state.player.node.position.add(new Vector3(0,1,0)))<.75**2){p.life=0;this.damagePlayer(state,p.damage)}}
    this.projectiles=this.projectiles.filter(p=>{if(p.life>0)return true;p.node.dispose();return false});this.enemyProjectiles=this.enemyProjectiles.filter(p=>{if(p.life>0)return true;p.node.dispose();return false})
  }
  tryFire(state){const w=state.weapon;if(!w||this.cooldown>0||state.reloading)return;if(w.kind==='melee'){this.cooldown=1/(w.rate*state.player.attackSpeed);this.melee(state,w);return}if(state.ammo<=0){this.bus.emit('weapon:empty');return}this.cooldown=1/(w.rate*state.player.attackSpeed);state.ammo--;this.bus.emit('weapon:fired',{weapon:w,ammo:state.ammo});const dir=this.camera.locked&&state.input.mouse.right?this.camera.locked.node.position.add(new Vector3(0,1,0)).subtract(state.player.node.position.add(new Vector3(0,1.15,0))).normalize():this.camera.camera.getForwardRay().direction.normalize();const origin=state.player.node.position.add(new Vector3(.45,1.15,0)).add(dir.scale(.7));for(let i=0;i<(w.pellets||1);i++){const d=dir.clone();if(w.spread){d.x+=(Math.random()-.5)*w.spread;d.y+=(Math.random()-.5)*w.spread*.3;d.z+=(Math.random()-.5)*w.spread;d.normalize()}const node=this.factory.createProjectile(state.rarityColor(w.rarity),w.kind==='grenade'?.16:.09);node.position.copyFrom(origin);this.projectiles.push({node,velocity:d.scale(w.speed),damage:w.damage*state.player.damage,life:(w.range||60)/w.speed,w})}this.camera.kick(.035)}
  melee(state,w){const f=this.camera.forward();let hit=false;for(const e of state.enemies){if(e.dead)continue;const v=e.node.position.subtract(state.player.node.position);const dist=v.length();v.y=0;if(dist<(w.range||3.2)+e.radius&&Vector3.Dot(v.normalize(),f)>.18){const crit=Math.random()<(state.player.crit||0),damage=w.damage*state.player.damage*state.player.melee*(crit?1.6:1);this.damageEnemy(e,damage,crit);hit=true}}this.bus.emit('weapon:melee',{hit});if(hit)this.camera.kick(.12)}
  damageEnemy(e,damage,crit=false){e.alerted=true;e.lastSeen=performance.now()/1000;e.hp-=damage;this.flashRed(e);this.bus.emit('enemy:hit',{enemy:e,damage,crit});this.camera.kick(crit?.085:.055);if(e.hp<=0&&!e.dead){e.dead=true;e.node.setEnabled(false);this.bus.emit('enemy:killed',e)}}
  flashRed(e){const mats=e.node.metadata?.flashMaterials||[];clearTimeout(e.flashTimer);for(const m of mats){if(!m.metadata)m.metadata={};if(!m.metadata.baseDiffuse)m.metadata.baseDiffuse=m.diffuseColor.clone();m.diffuseColor=new Color3(1,.035,.02);m.emissiveColor=new Color3(.32,0,0)}e.flashTimer=setTimeout(()=>{for(const m of mats){if(m.metadata?.baseDiffuse)m.diffuseColor.copyFrom(m.metadata.baseDiffuse);m.emissiveColor=Color3.Black()}},70)}
  spawnEnemyShot({enemy,dir}){if(!enemy||enemy.dead)return;const color='#'+(enemy.def.color||0xff5577).toString(16).padStart(6,'0'),node=this.factory.createProjectile(color,enemy.boss?.15:.11),origin=enemy.node.position.add(new Vector3(0,enemy.boss?2:1.1,0)),speed=enemy.def.ai==='sniper'?38:(enemy.boss?28:24);node.position.copyFrom(origin);this.enemyProjectiles.push({node,velocity:dir.normalize().scale(speed),damage:enemy.damage*(enemy.elite?1.18:1),life:5.5})}
  damagePlayer(state,damage){if(state.player.ifr>0)return;state.player.ifr=.22;state.player.hp=Math.max(0,state.player.hp-damage);this.camera.kick(.24);this.bus.emit('player:hit',{damage,hp:state.player.hp});if(state.player.hp<=0)this.bus.emit('player:dead')}
  clear(){for(const p of [...this.projectiles,...this.enemyProjectiles])p.node.dispose();this.projectiles=[];this.enemyProjectiles=[];this.pendingEnemyShots=[]}
}
