import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {CLASSES,RARITY,WEAPONS,ENEMIES,BOSSES,UPGRADES} from './data.js';

const $=s=>document.querySelector(s),hud=$('#hud'),modal=$('#modal');
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),pick=a=>a[(Math.random()*a.length)|0];
const wmap=Object.fromEntries(WEAPONS.map(w=>[w.id,w]));
const EXTRA=[
{name:'Ivory Drone',hp:300,speed:4.1,r:.78,color:0xf2f2e8,ai:'orbit',damage:26,xp:52,flying:true},
{name:'Azure Gunner',hp:360,speed:3.0,r:.9,color:0x4f9dff,ai:'burst',damage:30,xp:64},
{name:'Lime Oracle',hp:330,speed:2.9,r:.84,color:0xb5ff4f,ai:'fan',damage:29,xp:60},
{name:'Rose Blinker',hp:280,speed:4.8,r:.75,color:0xff789b,ai:'blink',damage:31,xp:58},
{name:'Gold Reactor',hp:520,speed:2.4,r:1.05,color:0xffcf55,ai:'radial',damage:34,xp:78},
{name:'Indigo Lancer',hp:410,speed:3.4,r:.9,color:0x6c63ff,ai:'sniper',damage:45,xp:72}
];
const POOL=[...ENEMIES,...EXTRA];
let scene,camera,renderer,clock,player,world,enemyGroup,bulletGroup,pickupGroup,weaponRig;
let enemies=[],bullets=[],enemyBullets=[],pickups=[],chests=[],shopItems=[],walls=[],orbitals=[];
let keys={},mouse={left:false,right:false},yaw=0,pitch=-.18,lockedTarget=null;
let floor=1,room=0,roomInFloor=0,roomClear=false,isShop=false,isBoss=false,difficulty=1,mapHalf=24;
const tmp=new THREE.Vector3();

function mat(color,rough=.7,metal=.12,emissive=0){return new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal,emissive,emissiveIntensity:emissive?.55:0})}
function init(){
 scene=new THREE.Scene();scene.background=new THREE.Color(0x252a32);scene.fog=new THREE.FogExp2(0x353b45,.003);
 camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.1,220);
 renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.15));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.45;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.BasicShadowMap;$('#game').appendChild(renderer.domElement);
 scene.add(new THREE.HemisphereLight(0xffffff,0x667080,2.7));const sun=new THREE.DirectionalLight(0xffffff,3.0);sun.position.set(10,20,8);sun.castShadow=true;sun.shadow.mapSize.set(768,768);sun.shadow.camera.left=-30;sun.shadow.camera.right=30;sun.shadow.camera.top=30;sun.shadow.camera.bottom=-30;scene.add(sun);const fill=new THREE.DirectionalLight(0xdce8ff,1.35);fill.position.set(-10,8,-10);scene.add(fill);
 world=new THREE.Group();enemyGroup=new THREE.Group();bulletGroup=new THREE.Group();pickupGroup=new THREE.Group();scene.add(world,enemyGroup,bulletGroup,pickupGroup);
 clock=new THREE.Clock();bind();chooseClass();animate();
}
function bind(){
 addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
 addEventListener('keydown',e=>{keys[e.code]=true;if(['Digit1','Digit2','Digit3'].includes(e.code)&&player){player.slot=+e.code.at(-1)-1;refreshHeldWeapon()}if(e.code==='KeyE'&&player)interact();if(e.code==='KeyR'&&player)reload()});addEventListener('keyup',e=>keys[e.code]=false);
 renderer.domElement.addEventListener('mousedown',e=>{if(e.button===0)mouse.left=true;if(e.button===2){mouse.right=true;lockedTarget=findVisibleLockTarget(48)}});addEventListener('mouseup',e=>{if(e.button===0)mouse.left=false;if(e.button===2){mouse.right=false;lockedTarget=null}});renderer.domElement.oncontextmenu=e=>e.preventDefault();
 renderer.domElement.addEventListener('click',()=>{if(!modal.classList.contains('show'))renderer.domElement.requestPointerLock?.()});document.addEventListener('mousemove',e=>{if(document.pointerLockElement===renderer.domElement&&!mouse.right){yaw-=e.movementX*.0021;pitch=clamp(pitch-e.movementY*.00165,-.55,.2)}})
}
function releaseMouse(){if(document.pointerLockElement)document.exitPointerLock?.()}function grabMouse(){if(!modal.classList.contains('show'))renderer.domElement.requestPointerLock?.()}
function chooseClass(){releaseMouse();modal.classList.add('show');modal.innerHTML=`<div class="card hero"><div class="eyebrow">OPERATIVE SELECT</div><h1>Class seç</h1><div class="grid">${Object.entries(CLASSES).map(([id,c])=>`<button class="choice" data-class="${id}"><span class="classdot" style="background:#${c.color.toString(16).padStart(6,'0')}"></span><h3>${c.name}</h3><p>${c.desc.replace(/aim assist/gi,'precision')}</p><small>HP ${c.hp} · SPD ${c.speed}</small></button>`).join('')}</div></div>`;modal.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>startGame(b.dataset.class))}
function startGame(id){const c=CLASSES[id];player={classId:id,class:c,mesh:makePlayer(c.color),yVel:0,onGround:true,hp:c.hp,maxHp:c.hp,speed:c.speed,damage:c.damage,crit:c.crit||.08,melee:c.melee||1,attackSpeed:1,bossDamage:1,pickup:1,killHeal:0,coins:0,xp:0,level:1,nextXp:90,slots:c.slots.map(id=>({id,ammo:wmap[id].mag??0,reload:0,cd:0})),slot:0,dash:0,dashMax:.9,ifr:0};scene.add(player.mesh);weaponRig=new THREE.Group();player.mesh.add(weaponRig);refreshHeldWeapon();closeModal(false);buildRoom()}
function makePlayer(color){const g=new THREE.Group(),armor=mat(color,.42,.34),dark=mat(0x242b36,.7,.32),mid=mat(0x66717f,.55,.3),visor=new THREE.MeshBasicMaterial({color:0xa8efff});
 const torso=new THREE.Mesh(new THREE.BoxGeometry(.9,1.0,.55),armor);torso.position.y=1.45;torso.castShadow=true;g.add(torso);
 const chest=new THREE.Mesh(new THREE.BoxGeometry(.98,.2,.62),dark);chest.position.set(0,1.68,.08);g.add(chest);
 const head=new THREE.Mesh(new THREE.SphereGeometry(.39,14,10),mid);head.position.y=2.25;g.add(head);
 const faceplate=new THREE.Mesh(new THREE.BoxGeometry(.52,.21,.09),dark);faceplate.position.set(0,2.25,.34);g.add(faceplate);
 const eye=new THREE.Mesh(new THREE.BoxGeometry(.33,.07,.02),visor);eye.position.set(0,2.29,.395);g.add(eye);
 for(const sx of [-1,1]){const sh=new THREE.Mesh(new THREE.BoxGeometry(.28,.24,.42),dark);sh.position.set(.61*sx,1.74,0);g.add(sh);const arm=new THREE.Mesh(new THREE.CapsuleGeometry(.11,.48,3,6),armor);arm.position.set(.62*sx,1.37,0);g.add(arm);const fore=new THREE.Mesh(new THREE.BoxGeometry(.2,.38,.24),mid);fore.position.set(.62*sx,1.03,.03);g.add(fore);const leg=new THREE.Mesh(new THREE.CapsuleGeometry(.14,.52,3,6),dark);leg.position.set(.25*sx,.58,0);g.add(leg);const boot=new THREE.Mesh(new THREE.BoxGeometry(.34,.25,.5),mid);boot.position.set(.25*sx,.17,.08);g.add(boot)}
 const pack=new THREE.Mesh(new THREE.BoxGeometry(.55,.72,.22),dark);pack.position.set(0,1.45,-.4);g.add(pack);return g}
function currentWeapon(){return wmap[player.slots[player.slot].id]}
function refreshHeldWeapon(){if(!weaponRig||!player)return;weaponRig.clear();const w=currentWeapon(),base=mat(0x343b47,.35,.65),glow=new THREE.MeshBasicMaterial({color:RARITY[w.rarity]?.color||0xffffff}),root=new THREE.Group();if(w.kind==='melee'){const grip=new THREE.Mesh(new THREE.CylinderGeometry(.045,.055,.5,6),base);grip.rotation.x=Math.PI/2;root.add(grip);const len=w.id==='scythe'?1.35:w.id==='hammer'?.9:1.12,blade=new THREE.Mesh(w.id==='hammer'?new THREE.BoxGeometry(.48,.28,.3):new THREE.BoxGeometry(.08,.09,len),w.id==='hammer'?base:glow);blade.position.z=-len*.55;root.add(blade)}else{const body=new THREE.Mesh(new THREE.BoxGeometry(.23,.2,.78),base);body.position.z=-.3;root.add(body);const barrel=new THREE.Mesh(new THREE.CylinderGeometry(.035,.05,.6,6),glow);barrel.rotation.x=Math.PI/2;barrel.position.z=-.84;root.add(barrel)}root.position.set(.63,1.3,.12);root.rotation.y=Math.PI;weaponRig.add(root)}
function clearGroup(g){while(g.children.length){const o=g.children.pop();o.traverse?.(n=>{n.geometry?.dispose();if(Array.isArray(n.material))n.material.forEach(m=>m.dispose());else n.material?.dispose()})}}
function buildRoom(){clearGroup(world);clearGroup(enemyGroup);clearGroup(bulletGroup);clearGroup(pickupGroup);enemies=[];bullets=[];enemyBullets=[];pickups=[];chests=[];shopItems=[];walls=[];orbitals=[];roomClear=false;roomInFloor=room%12;isBoss=roomInFloor===11;isShop=!isBoss&&roomInFloor>0&&roomInFloor%4===3;floor=Math.floor(room/12)+1;difficulty=1+floor*.4+roomInFloor*.11;mapHalf=24+Math.min(4,floor);player.mesh.position.set(0,0,mapHalf-6);makeRoom();if(isShop)makeShop();else if(isBoss)spawnBoss();else spawnWave();notice(`DECK ${floor} · ROOM ${roomInFloor+1}/12`)}
function makeRoom(){const floorMat=mat(0x777f89,.85,.08),wallMat=mat(0xa0a5ad,.72,.08);const fm=new THREE.Mesh(new THREE.PlaneGeometry(mapHalf*2,mapHalf*2),floorMat);fm.rotation.x=-Math.PI/2;fm.receiveShadow=true;world.add(fm);const addWall=(x,z,w,d,h=4.8)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),wallMat);m.position.set(x,h/2,z);m.castShadow=m.receiveShadow=true;world.add(m);walls.push({x,z,w,d,h})};
 addWall(0,mapHalf,mapHalf*2,1);addWall(-mapHalf,0,1,mapHalf*2);addWall(mapHalf,0,1,mapHalf*2);addWall(-mapHalf*.62,-mapHalf,mapHalf*.65,1);addWall(mapHalf*.62,-mapHalf,mapHalf*.65,1);
 const variant=room%4;if(variant===1){addWall(-8,0,1.4,10);addWall(8,0,1.4,10)}else if(variant===2){for(const x of [-8,8])for(const z of [-7,7])addWall(x,z,1.5,1.5)}else if(variant===3){addWall(0,1,12,1.2)}
 for(const x of [-mapHalf+4,mapHalf-4])for(const z of [-mapHalf+5,0,mapHalf-5]){const lamp=new THREE.Mesh(new THREE.BoxGeometry(.8,.12,.35),new THREE.MeshBasicMaterial({color:0xffffff}));lamp.position.set(x,3.9,z);world.add(lamp)}}
function enemyModel(def,boss=false){const g=new THREE.Group(),main=mat(def.color,.5,.15),dark=mat(0x333944,.75,.12);const body=new THREE.Mesh(new THREE.CapsuleGeometry(boss?1.05:def.r*.7,boss?1.2:.62,4,7),main);body.position.y=boss?1.9:1.0;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(boss?.62:.38,10,8),main);head.position.y=boss?3.15:1.82;g.add(head);for(const x of [-.15,.15]){const eye=new THREE.Mesh(new THREE.SphereGeometry(boss?.11:.075,7,5),new THREE.MeshBasicMaterial({color:0xffffff}));eye.scale.z=.55;eye.position.set(x*(boss?2:1),head.position.y+.05,boss?.58:.35);g.add(eye);const p=new THREE.Mesh(new THREE.SphereGeometry(boss?.045:.028,6,4),new THREE.MeshBasicMaterial({color:0x11151c}));p.position.set(x*(boss?2:1),head.position.y+.05,boss?.64:.39);g.add(p)}const sh=new THREE.Mesh(new THREE.BoxGeometry(boss?2.2:1.1,.16,.44),dark);sh.position.set(0,body.position.y+.45,0);g.add(sh);return g}
function spawnEnemy(def=pick(POOL)){const scale=difficulty*(1+.06*floor),e={...def,hp:def.hp*scale,maxHp:def.hp*scale,damage:def.damage*(1+.08*floor),mesh:enemyModel(def),cd:rand(.3,1.2),t:rand(0,5),dead:false};let tries=0;do{e.mesh.position.set(rand(-mapHalf+3,mapHalf-3),0,rand(-mapHalf+5,4));tries++}while(collidesWalls(e.mesh.position,e.r+.2)&&tries<20);enemyGroup.add(e.mesh);enemies.push(e)}
function spawnWave(){const n=Math.min(10,4+Math.floor(roomInFloor*.35)+Math.floor(floor*.4));for(let i=0;i<n;i++)spawnEnemy(POOL[(Math.random()*Math.min(POOL.length,7+floor*2))|0]);if(Math.random()<.5)spawnChest(rand(-10,10),rand(-5,8))}
function spawnBoss(){const d=BOSSES[(floor-1)%BOSSES.length],e={...d,hp:d.hp*difficulty,maxHp:d.hp*difficulty,r:1.6,mesh:enemyModel({...d,r:1.6},true),cd:.8,t:0,boss:true,dead:false,damage:36+floor*7};e.mesh.position.set(0,0,-mapHalf+8);enemyGroup.add(e.mesh);enemies.push(e);notice(d.name,2)}
function spawnChest(x,z){const g=new THREE.Group(),b=new THREE.Mesh(new THREE.BoxGeometry(1.7,.75,1.1),mat(0x66576d,.55,.22)),lid=new THREE.Mesh(new THREE.BoxGeometry(1.75,.24,1.12),mat(0x444b56,.4,.45));b.position.y=.42;lid.position.y=.91;g.add(b,lid);g.position.set(x,0,z);world.add(g);chests.push({mesh:g,opened:false})}
function makeShop(){roomClear=true;for(const x of [-7,0,7]){const w=pick(WEAPONS),cost=Math.round(32+(WEAPONS.indexOf(w)+1)*6+floor*7),ped=new THREE.Mesh(new THREE.CylinderGeometry(.9,1,.6,10),mat(0x555d67,.5,.35));ped.position.set(x,.3,1);world.add(ped);shopItems.push({x,z:1,w,cost,bought:false,ped})}}
function weaponHTML(w){const r=RARITY[w.rarity];return `<span class="rarity" style="color:${r.color}">${r.label||w.rarity}</span><h3>${w.name}</h3><b>${w.type}</b><p>${w.desc.replace(/aim assist/gi,'precision')}</p>`}
function openChest(c){if(c.opened)return;c.opened=true;world.remove(c.mesh);showChoices('Cache',[pick(WEAPONS),pick(WEAPONS),pick(WEAPONS)].map(w=>({label:weaponHTML(w),action:()=>{replaceWeapon(w.id);closeModal()}})),true)}
function replaceWeapon(id){player.slots[player.slot]={id,ammo:wmap[id].mag??0,reload:0,cd:0};refreshHeldWeapon()}
function showChoices(title,items,skip=false){releaseMouse();modal.classList.add('show');modal.innerHTML=`<div class="card"><h2>${title}</h2><div class="grid">${items.map((it,i)=>`<button class="choice" data-i="${i}">${it.label}</button>`).join('')}${skip?'<button class="choice" data-skip><h3>Skip</h3></button>':''}</div></div>`;modal.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>items[+b.dataset.i].action());modal.querySelector('[data-skip]')?.addEventListener('click',()=>closeModal())}
function closeModal(relock=true){modal.classList.remove('show');if(relock)setTimeout(grabMouse,0)}
function interact(){for(const c of chests)if(!c.opened&&c.mesh.position.distanceTo(player.mesh.position)<3)return openChest(c);if(isShop){for(const it of shopItems){if(!it.bought&&Math.hypot(player.mesh.position.x-it.x,player.mesh.position.z-it.z)<2.5){if(player.coins<it.cost)return notice('Yetersiz kredi');player.coins-=it.cost;it.bought=true;replaceWeapon(it.w.id);return}}}}
function nextRoom(){room++;player.hp=Math.min(player.maxHp,player.hp+player.maxHp*.08);buildRoom()}
function reload(){const s=player.slots[player.slot],w=currentWeapon();if(w.kind==='melee'||w.kind==='orbital'||s.reload>0)return;s.reload=w.reload}
function cameraForward(){return new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(-pitch),Math.cos(yaw)*Math.cos(pitch)).normalize()}
function findVisibleLockTarget(max=48){let best=null,bd=max;for(const e of enemies)if(!e.dead){const worldPos=e.mesh.position.clone().add(new THREE.Vector3(0,1.2,0));const ndc=worldPos.clone().project(camera);if(ndc.z<-1||ndc.z>1||Math.abs(ndc.x)>.92||Math.abs(ndc.y)>.88)continue;if(segmentHitsWall(camera.position,worldPos,.08))continue;const d=e.mesh.position.distanceTo(player.mesh.position);if(d<bd){bd=d;best=e}}return best}
function aimDirection(){if(mouse.right){const p=new THREE.Vector3(.08,0,.5).unproject(camera);return p.sub(camera.position).normalize()}return cameraForward()}
function fire(){const s=player.slots[player.slot],w=currentWeapon();if(s.cd>0||s.reload>0)return;s.cd=1/(w.rate*player.attackSpeed);if(w.kind==='melee')return melee(w);if(w.kind==='orbital')return spawnOrbital(w);if(s.ammo<=0)return reload();s.ammo--;const dir=aimDirection(),origin=player.mesh.position.clone().add(new THREE.Vector3(.5,1.35,0)).addScaledVector(dir,.7);if(w.kind==='beam')return beamShot(origin,dir,w);for(let i=0;i<(w.pellets||1);i++){const d=dir.clone();if(w.spread){d.x+=rand(-w.spread,w.spread);d.y+=rand(-w.spread*.3,w.spread*.3);d.z+=rand(-w.spread,w.spread);d.normalize()}spawnBullet(origin,d,w)}}
function spawnBullet(origin,dir,w){const m=new THREE.Mesh(new THREE.SphereGeometry(w.kind==='grenade'?.17:.085,6,4),new THREE.MeshBasicMaterial({color:RARITY[w.rarity]?.color||0xffffff}));m.position.copy(origin);bulletGroup.add(m);bullets.push({mesh:m,vel:dir.clone().multiplyScalar(w.speed),life:(w.range||60)/Math.max(1,w.speed),w,damage:w.damage*player.damage,pierce:w.pierce||0})}
function beamShot(origin,dir,w){let nearest=null,nd=w.range;for(const e of enemies)if(!e.dead){const to=e.mesh.position.clone().add(new THREE.Vector3(0,1,0)).sub(origin),proj=to.dot(dir);if(proj>0&&proj<nd&&to.clone().sub(dir.clone().multiplyScalar(proj)).length()<e.r+.7){nearest=e;nd=proj}}if(nearest&&!segmentHitsWall(origin,nearest.mesh.position.clone().add(new THREE.Vector3(0,1,0))))hitEnemy(nearest,w.damage*player.damage*(nearest.boss?player.bossDamage:1))}
function spawnOrbital(w){for(let i=0;i<3;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(.17,6,4),new THREE.MeshBasicMaterial({color:RARITY[w.rarity]?.color||0xffffff}));bulletGroup.add(m);orbitals.push({mesh:m,angle:i*Math.PI*2/3,life:7,damage:w.damage})}}
function melee(w){const forward=new THREE.Vector3(Math.sin(player.mesh.rotation.y),0,Math.cos(player.mesh.rotation.y)),origin=player.mesh.position.clone(),range=(w.range||3)*1.4,maxAngle=(w.arc||1.8)/2+.25;for(const e of enemies)if(!e.dead){const flat=e.mesh.position.clone().sub(origin);flat.y=0;if(flat.length()<=range+e.r&&Math.acos(clamp(flat.normalize().dot(forward),-1,1))<=maxAngle)hitEnemy(e,w.damage*player.damage*player.melee*(e.boss?player.bossDamage:1))}}
function hitEnemy(e,d){e.hp-=d;if(e.hp<=0&&!e.dead){e.dead=true;const pos=e.mesh.position.clone();enemyGroup.remove(e.mesh);player.xp+=e.xp||45;spawnCoin(pos,Math.max(3,Math.round((e.xp||40)/9)));player.hp=Math.min(player.maxHp,player.hp+player.killHeal);checkLevel()}}
function spawnCoin(pos,v){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(.15,0),new THREE.MeshBasicMaterial({color:0xffd25a}));m.position.copy(pos).add(new THREE.Vector3(0,.4,0));pickupGroup.add(m);pickups.push({mesh:m,v})}
function checkLevel(){while(player.xp>=player.nextXp){player.xp-=player.nextXp;player.level++;player.nextXp=Math.floor(player.nextXp*1.22+25);const opts=[...UPGRADES].filter(u=>!u.name.toLowerCase().includes('optics')).sort(()=>Math.random()-.5).slice(0,3);showChoices(`Level ${player.level}`,opts.map(u=>({label:`<h3>${u.name}</h3><p>${u.desc.replace(/aim assist/gi,'precision')}</p>`,action:()=>{u.apply(player);closeModal()}})))}}
function collidesWalls(p,r=.6){return walls.some(w=>Math.abs(p.x-w.x)<w.w/2+r&&Math.abs(p.z-w.z)<w.d/2+r)}function resolveWall(p,w,r){if(Math.abs(p.x-w.x)<w.w/2+r&&Math.abs(p.z-w.z)<w.d/2+r){const dx=w.w/2+r-Math.abs(p.x-w.x),dz=w.d/2+r-Math.abs(p.z-w.z);if(dx<dz)p.x+=Math.sign(p.x-w.x||1)*dx;else p.z+=Math.sign(p.z-w.z||1)*dz}}function segmentHitsWall(a,b,r=.06){const steps=Math.max(2,Math.ceil(a.distanceTo(b)/1.0));for(const w of walls)for(let i=1;i<=steps;i++){const p=tmp.copy(a).lerp(b,i/steps);if(Math.abs(p.x-w.x)<w.w/2+r&&Math.abs(p.z-w.z)<w.d/2+r&&p.y<w.h+.2)return true}return false}
function movePlayer(dt){const f=new THREE.Vector3(Math.sin(yaw),0,Math.cos(yaw)),r=new THREE.Vector3(-f.z,0,f.x),dir=new THREE.Vector3();if(keys.KeyW)dir.add(f);if(keys.KeyS)dir.sub(f);if(keys.KeyD)dir.add(r);if(keys.KeyA)dir.sub(r);if(dir.lengthSq())dir.normalize();if(keys.ShiftLeft&&player.dash<=0){player.dash=player.dashMax;player.ifr=.2;dir.multiplyScalar(2.5)}player.dash=Math.max(0,player.dash-dt);player.mesh.position.addScaledVector(dir,player.speed*dt);player.mesh.position.x=clamp(player.mesh.position.x,-mapHalf+1.3,mapHalf-1.3);player.mesh.position.z=clamp(player.mesh.position.z,-mapHalf-1.8,mapHalf-1.3);for(const w of walls)resolveWall(player.mesh.position,w,.58);if(keys.Space&&player.onGround){player.yVel=8.5;player.onGround=false}player.yVel-=21*dt;player.mesh.position.y+=player.yVel*dt;if(player.mesh.position.y<=0){player.mesh.position.y=0;player.yVel=0;player.onGround=true}if(mouse.right)player.mesh.rotation.y=yaw;else if(dir.lengthSq())player.mesh.rotation.y=Math.atan2(dir.x,dir.z);if(roomClear&&player.mesh.position.z<-mapHalf-.8)nextRoom()}
function updateCamera(dt){if(mouse.right&&lockedTarget&&!lockedTarget.dead){const v=lockedTarget.mesh.position.clone().sub(player.mesh.position);yaw=Math.atan2(v.x,v.z);pitch=clamp(-Math.atan2(v.y+.5,Math.hypot(v.x,v.z)),-.35,.08)}const f=cameraForward(),right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw));const anchor=player.mesh.position.clone().add(new THREE.Vector3(0,1.15,0));let desired=anchor.clone().add(new THREE.Vector3(-Math.sin(yaw)*(mouse.right?5.7:9.2),mouse.right?3.2:4.4,-Math.cos(yaw)*(mouse.right?5.7:9.2)));if(mouse.right)desired.addScaledVector(right,.9);let safe=desired.clone();if(segmentHitsWall(anchor,desired,.18)){for(let t=.88;t>.18;t-=.08){const p=anchor.clone().lerp(desired,t);if(!segmentHitsWall(anchor,p,.15)){safe=p;break}}}camera.position.lerp(safe,1-Math.pow(.0007,dt));let look=player.mesh.position.clone().add(new THREE.Vector3(0,.35,0)).addScaledVector(f,mouse.right?10:6.5);if(mouse.right)look.addScaledVector(right,-.45);camera.lookAt(look)}
function enemyShoot(e,dir,speed=12,count=1,spread=.12){for(let i=0;i<count;i++){const d=dir.clone();if(count>1){const a=(i-(count-1)/2)*spread,c=Math.cos(a),s=Math.sin(a),x=d.x*c-d.z*s,z=d.x*s+d.z*c;d.x=x;d.z=z}const m=new THREE.Mesh(new THREE.SphereGeometry(.12,6,4),new THREE.MeshBasicMaterial({color:e.color||0xff5a75}));m.position.copy(e.mesh.position).add(new THREE.Vector3(0,1,0));bulletGroup.add(m);enemyBullets.push({mesh:m,vel:d.normalize().multiplyScalar(speed),life:6,damage:e.damage||24})}}
function ring(e,n=14,s=9,o=0){for(let i=0;i<n;i++){const a=o+i*Math.PI*2/n;enemyShoot(e,new THREE.Vector3(Math.sin(a),0,Math.cos(a)),s)}}
function updateEnemies(dt){for(const e of enemies)if(!e.dead){e.t+=dt;e.cd-=dt;const to=player.mesh.position.clone().sub(e.mesh.position),dist=to.length(),dir=to.normalize(),spd=e.speed*Math.min(1.8,1+.08*floor),old=e.mesh.position.clone();if(e.boss)bossAI(e,dir,dt);else if(e.ai==='chase')e.mesh.position.addScaledVector(dir,spd*dt);else if(e.ai==='orbit'){e.mesh.position.addScaledVector(new THREE.Vector3(-dir.z,0,dir.x),spd*dt);if(e.cd<=0){enemyShoot(e,dir,13);e.cd=1.05/Math.min(2,difficulty)}}else if(e.ai==='shooter'||e.ai==='sniper'){if(dist>11)e.mesh.position.addScaledVector(dir,spd*.5*dt);if(e.cd<=0){enemyShoot(e,dir,e.ai==='sniper'?19:13,e.ai==='sniper'?1:3,.1);e.cd=(e.ai==='sniper'?1.7:1)/Math.min(2,difficulty)}}else if(e.ai==='radial'&&e.cd<=0){ring(e,12+Math.min(8,floor),9,e.t);e.cd=1.5/Math.min(2,difficulty)}else if(e.ai==='charge'){if(e.cd<=0){e.charge=.5;e.cd=2}if(e.charge>0){e.mesh.position.addScaledVector(dir,spd*3.2*dt);e.charge-=dt}}else if(e.ai==='spiral'&&e.cd<=0){for(let i=0;i<5;i++){const a=e.t+i*Math.PI*2/5;enemyShoot(e,new THREE.Vector3(Math.sin(a),0,Math.cos(a)),10)}e.cd=.34/Math.min(2,difficulty)}else if(e.ai==='rings'&&e.cd<=0){ring(e,18,9,e.t);e.cd=1.5/Math.min(2,difficulty)}else if(e.ai==='burst'&&e.cd<=0){enemyShoot(e,dir,14,5,.11);e.cd=.9/Math.min(2,difficulty)}else if(e.ai==='blink'&&e.cd<=0){const np=player.mesh.position.clone().add(new THREE.Vector3(rand(-8,8),0,rand(-8,8)));if(!collidesWalls(np,e.r))e.mesh.position.copy(np);e.cd=1.8}else if(e.ai==='satellite'&&e.cd<=0){ring(e,8,8,e.t);enemyShoot(e,dir,14);e.cd=.9/Math.min(2,difficulty)}else if(e.ai==='fan'&&e.cd<=0){enemyShoot(e,dir,13,7,.2);e.cd=1.05/Math.min(2,difficulty)};for(const w of walls)resolveWall(e.mesh.position,w,e.r*.7);if(segmentHitsWall(old,e.mesh.position,e.r*.2))e.mesh.position.copy(old);if(dist<e.r+.7)hurtPlayer((e.damage||24)*dt*1.8);e.mesh.rotation.y=Math.atan2(dir.x,dir.z)}}
function bossAI(e,dir,dt){const phase=1+Math.floor((1-e.hp/e.maxHp)*3);if(e.cd<=0){ring(e,16+phase*4,10+phase,e.t);enemyShoot(e,dir,16,3+phase*2,.11);e.cd=Math.max(.6,1.6-phase*.18)}e.mesh.position.addScaledVector(new THREE.Vector3(-dir.z,0,dir.x),1.4*dt);for(const w of walls)resolveWall(e.mesh.position,w,1.2)}
function updateBullets(dt){for(const b of bullets){const old=b.mesh.position.clone();if(b.w.kind==='homing'){const e=findNearestFrom(b.mesh.position,45);if(e){const desired=e.mesh.position.clone().add(new THREE.Vector3(0,1,0)).sub(b.mesh.position).normalize().multiplyScalar(b.w.speed);b.vel.lerp(desired,clamp(b.w.turn*dt,0,1))}}b.mesh.position.addScaledVector(b.vel,dt);b.life-=dt;if(segmentHitsWall(old,b.mesh.position,.1)){b.life=0;continue}for(const e of enemies)if(!e.dead&&b.mesh.position.distanceTo(e.mesh.position.clone().add(new THREE.Vector3(0,1,0)))<e.r+.32){hitEnemy(e,b.damage*(e.boss?player.bossDamage:1));if(b.pierce-->0){}else{b.life=0;break}}}for(const b of enemyBullets){const old=b.mesh.position.clone();b.mesh.position.addScaledVector(b.vel,dt);b.life-=dt;if(segmentHitsWall(old,b.mesh.position,.1)){b.life=0;continue}if(b.mesh.position.distanceTo(player.mesh.position.clone().add(new THREE.Vector3(0,1,0)))<.66){hurtPlayer(b.damage);b.life=0}}for(const o of orbitals){o.angle+=dt*3.6;o.life-=dt;o.mesh.position.copy(player.mesh.position).add(new THREE.Vector3(Math.cos(o.angle)*2.3,1.3,Math.sin(o.angle)*2.3));for(const e of enemies)if(!e.dead&&o.mesh.position.distanceTo(e.mesh.position)<e.r+.4)hitEnemy(e,o.damage*dt*3.2)}bullets=bullets.filter(b=>{if(b.life<=0){bulletGroup.remove(b.mesh);return false}return true});enemyBullets=enemyBullets.filter(b=>{if(b.life<=0){bulletGroup.remove(b.mesh);return false}return true});orbitals=orbitals.filter(o=>{if(o.life<=0){bulletGroup.remove(o.mesh);return false}return true})}
function findNearestFrom(pos,max){let best=null,bd=max;for(const e of enemies)if(!e.dead){const d=e.mesh.position.distanceTo(pos);if(d<bd){bd=d;best=e}}return best}function hurtPlayer(d){if(player.ifr>0)return;player.hp-=d;player.ifr=.18;if(player.hp<=0)gameOver()}function gameOver(){releaseMouse();modal.classList.add('show');modal.innerHTML=`<div class="card death"><h1>SYSTEM FAILURE</h1><p>Deck ${floor} · Room ${roomInFloor+1}</p><button id="restart" class="choice"><h3>RESTART</h3></button></div>`;$('#restart').onclick=()=>location.reload()}
function updatePickups(dt){for(const p of pickups){p.mesh.rotation.y+=dt*3;const to=player.mesh.position.clone().add(new THREE.Vector3(0,.5,0)).sub(p.mesh.position),d=to.length(),radius=7*player.pickup;if(d<radius)p.mesh.position.addScaledVector(to.normalize(),dt*(8+radius-d));if(d<.75){player.coins+=p.v;p.dead=true;pickupGroup.remove(p.mesh)}}pickups=pickups.filter(p=>!p.dead)}
function drawHud(){const w=currentWeapon(),s=player.slots[player.slot];hud.innerHTML=`<div class="topbar"><div><b>DECK ${floor} · ROOM ${roomInFloor+1}/12</b></div><div class="credits">◈ ${player.coins}</div></div><div class="health"><span>HP ${Math.ceil(player.hp)}/${Math.ceil(player.maxHp)}</span><i style="width:${clamp(player.hp/player.maxHp*100,0,100)}%"></i></div><div class="reticle ${mouse.right&&lockedTarget?'locked':''}"></div><div class="slots">${player.slots.map((q,i)=>{const ww=wmap[q.id];return`<div class="slot ${i===player.slot?'active':''}"><small>${i+1}</small><b style="color:${RARITY[ww.rarity].color}">${ww.name}</b><span>${ww.type}</span></div>`}).join('')}</div><div class="weaponinfo"><b>${w.name}</b><span>${w.kind==='melee'?'MELEE':`${s.reload>0?'RELOADING':s.ammo+'/'+(w.mag||0)}`}</span></div><div class="controls">WASD · LMB fire · RMB visible target lock · E interact · Space · Shift</div>`}
function notice(t,time=1.3){const n=document.createElement('div');n.className='notice';n.textContent=t;document.body.appendChild(n);setTimeout(()=>n.remove(),time*1000)}
function update(dt){if(!player||modal.classList.contains('show'))return;for(const s of player.slots){s.cd=Math.max(0,s.cd-dt);if(s.reload>0){s.reload-=dt;if(s.reload<=0)s.ammo=wmap[s.id].mag??0}}player.ifr=Math.max(0,player.ifr-dt);movePlayer(dt);if(mouse.left)fire();updateCamera(dt);updateBullets(dt);updateEnemies(dt);updatePickups(dt);if(!roomClear&&enemies.every(e=>e.dead)){roomClear=true;notice(isBoss?'BOSS DOWN · EXIT OPEN':'ROOM CLEAR · EXIT OPEN')}drawHud()}
function animate(){requestAnimationFrame(animate);const dt=Math.min(.033,clock.getDelta());if(player&&!modal.classList.contains('show')){update(dt);renderer.render(scene,camera)}else if(player)renderer.render(scene,camera)}
init();