import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {CLASSES,RARITY,WEAPONS,ENEMIES,BOSSES,UPGRADES} from './data.js';

const $=s=>document.querySelector(s), hud=$('#hud'), modal=$('#modal');
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), rand=(a,b)=>a+Math.random()*(b-a), pick=a=>a[(Math.random()*a.length)|0];
const wmap=Object.fromEntries(WEAPONS.map(w=>[w.id,w]));
const EXTRA=[
{name:'Ivory Drone',hp:300,speed:4.1,r:.78,color:0xf2f2e8,ai:'orbit',damage:26,xp:52,flying:true},
{name:'Azure Gunner',hp:360,speed:3.0,r:.9,color:0x4f9dff,ai:'burst',damage:30,xp:64},
{name:'Lime Oracle',hp:330,speed:2.9,r:.84,color:0xb5ff4f,ai:'fan',damage:29,xp:60},
{name:'Rose Blinker',hp:280,speed:4.8,r:.75,color:0xff789b,ai:'blink',damage:31,xp:58},
{name:'Gold Reactor',hp:520,speed:2.4,r:1.05,color:0xffcf55,ai:'radial',damage:34,xp:78},
{name:'Indigo Lancer',hp:410,speed:3.4,r:.9,color:0x6c63ff,ai:'sniper',damage:45,xp:72}
];
const POOL=[...ENEMIES,...EXTRA];
let scene,camera,renderer,clock,player,world,enemyGroup,bulletGroup,pickupGroup,fxGroup,weaponRig;
let enemies=[],bullets=[],enemyBullets=[],pickups=[],chests=[],shopItems=[],walls=[],orbitals=[];
let keys={},mouse={left:false,right:false},yaw=0,pitch=-.18,lockedTarget=null;
let floor=1,room=0,roomInFloor=0,roomClear=false,isShop=false,isBoss=false,difficulty=1,mapHalf=24;
let shake=0,hitStop=0,lockRefresh=0;
const tmpA=new THREE.Vector3();

function mat(color,rough=.72,metal=.08,emissive=0){return new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal,emissive,emissiveIntensity:emissive?.45:0})}
function init(){scene=new THREE.Scene();scene.background=new THREE.Color(0x2b3038);scene.fog=new THREE.FogExp2(0x414854,.0027);camera=new THREE.PerspectiveCamera(67,innerWidth/innerHeight,.1,220);renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.15));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.5;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.BasicShadowMap;$('#game').appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x707987,2.8));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(12,20,10);sun.castShadow=true;sun.shadow.mapSize.set(768,768);sun.shadow.camera.left=-30;sun.shadow.camera.right=30;sun.shadow.camera.top=30;sun.shadow.camera.bottom=-30;scene.add(sun);const fill=new THREE.DirectionalLight(0xe3ecff,1.15);fill.position.set(-12,9,-8);scene.add(fill);world=new THREE.Group();enemyGroup=new THREE.Group();bulletGroup=new THREE.Group();pickupGroup=new THREE.Group();fxGroup=new THREE.Group();scene.add(world,enemyGroup,bulletGroup,pickupGroup,fxGroup);clock=new THREE.Clock();bind();chooseClass();animate()}
function bind(){addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});addEventListener('keydown',e=>{keys[e.code]=true;if(['Digit1','Digit2','Digit3'].includes(e.code)&&player){player.slot=+e.code.at(-1)-1;refreshHeldWeapon()}if(e.code==='KeyE'&&player)interact();if(e.code==='KeyR'&&player)reload()});addEventListener('keyup',e=>keys[e.code]=false);renderer.domElement.addEventListener('mousedown',e=>{if(e.button===0)mouse.left=true;if(e.button===2){mouse.right=true;lockedTarget=findVisibleLockTarget(52);lockRefresh=0}});addEventListener('mouseup',e=>{if(e.button===0)mouse.left=false;if(e.button===2){mouse.right=false;lockedTarget=null}});renderer.domElement.oncontextmenu=e=>e.preventDefault();renderer.domElement.addEventListener('click',()=>{if(!modal.classList.contains('show'))renderer.domElement.requestPointerLock?.()});document.addEventListener('mousemove',e=>{if(document.pointerLockElement!==renderer.domElement)return;yaw-=e.movementX*.00215;pitch=clamp(pitch-e.movementY*.0018,-.72,.34)})}
function releaseMouse(){if(document.pointerLockElement)document.exitPointerLock?.()}function grabMouse(){if(!modal.classList.contains('show'))renderer.domElement.requestPointerLock?.()}
function chooseClass(){releaseMouse();modal.classList.add('show');modal.innerHTML=`<div class="card hero"><div class="eyebrow">OPERATIVE SELECT</div><h1>Class seç</h1><div class="grid">${Object.entries(CLASSES).map(([id,c])=>`<button class="choice" data-class="${id}"><span class="classdot" style="background:#${c.color.toString(16).padStart(6,'0')}"></span><h3>${c.name}</h3><p>${c.desc.replace(/aim assist/gi,'precision')}</p><small>HP ${c.hp} · SPD ${c.speed}</small></button>`).join('')}</div></div>`;modal.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>startGame(b.dataset.class))}
function startGame(id){const c=CLASSES[id];player={classId:id,class:c,mesh:makePlayer(c.color),yVel:0,onGround:true,hp:c.hp,maxHp:c.hp,speed:c.speed,damage:c.damage,crit:c.crit||.08,melee:c.melee||1,attackSpeed:1,bossDamage:1,pickup:1,killHeal:0,coins:0,xp:0,level:1,nextXp:90,slots:c.slots.map(id=>({id,ammo:wmap[id].mag??0,reload:0,cd:0})),slot:0,dash:0,dashMax:.9,ifr:0};scene.add(player.mesh);weaponRig=new THREE.Group();player.mesh.add(weaponRig);refreshHeldWeapon();closeModal(false);buildRoom()}
function makePlayer(color){const g=new THREE.Group(),skin=mat(0xb98568,.78,.01),cloth=mat(color,.78,.03),dark=mat(0x22252b,.8,.04),hair=mat(0x171719,.9,0);const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.34,.78,5,8),cloth);torso.position.y=1.38;torso.scale.set(1.18,1,.82);torso.castShadow=true;g.add(torso);const hips=new THREE.Mesh(new THREE.BoxGeometry(.62,.25,.38),dark);hips.position.y=.88;g.add(hips);const neck=new THREE.Mesh(new THREE.CylinderGeometry(.12,.14,.18,8),skin);neck.position.y=1.96;g.add(neck);const head=new THREE.Mesh(new THREE.SphereGeometry(.34,14,10),skin);head.position.y=2.22;head.scale.set(.92,1.05,.92);head.castShadow=true;g.add(head);const hairCap=new THREE.Mesh(new THREE.SphereGeometry(.35,12,8,0,Math.PI*2,0,Math.PI*.55),hair);hairCap.position.set(0,2.29,-.01);g.add(hairCap);for(const x of [-.115,.115]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.042,7,5),new THREE.MeshBasicMaterial({color:0xf9fbff}));eye.position.set(x,2.25,.313);g.add(eye);const pupil=new THREE.Mesh(new THREE.SphereGeometry(.017,6,4),new THREE.MeshBasicMaterial({color:0x17191d}));pupil.position.set(x,2.25,.349);g.add(pupil)}const mouth=new THREE.Mesh(new THREE.BoxGeometry(.11,.018,.018),new THREE.MeshBasicMaterial({color:0x5a2c2b}));mouth.position.set(0,2.11,.326);g.add(mouth);for(const sx of [-1,1]){const upper=new THREE.Mesh(new THREE.CapsuleGeometry(.09,.42,3,6),cloth);upper.position.set(.47*sx,1.44,0);upper.rotation.z=sx*.08;g.add(upper);const fore=new THREE.Mesh(new THREE.CapsuleGeometry(.085,.37,3,6),skin);fore.position.set(.49*sx,1.02,.02);g.add(fore);const hand=new THREE.Mesh(new THREE.SphereGeometry(.105,8,6),skin);hand.position.set(.49*sx,.77,.04);g.add(hand);const thigh=new THREE.Mesh(new THREE.CapsuleGeometry(.13,.5,3,6),dark);thigh.position.set(.21*sx,.55,0);g.add(thigh);const shin=new THREE.Mesh(new THREE.CapsuleGeometry(.11,.42,3,6),dark);shin.position.set(.21*sx,.18,0);g.add(shin);const shoe=new THREE.Mesh(new THREE.BoxGeometry(.28,.16,.46),dark);shoe.position.set(.21*sx,.04,.09);g.add(shoe)}const jacket=new THREE.Mesh(new THREE.BoxGeometry(.8,.18,.5),dark);jacket.position.set(0,1.67,-.02);g.add(jacket);return g}
function currentWeapon(){return wmap[player.slots[player.slot].id]}
function refreshHeldWeapon(){if(!weaponRig||!player)return;weaponRig.clear();const w=currentWeapon(),base=mat(0x343b47,.35,.6),glow=new THREE.MeshBasicMaterial({color:RARITY[w.rarity]?.color||0xffffff}),root=new THREE.Group();if(w.kind==='melee'){const grip=new THREE.Mesh(new THREE.CylinderGeometry(.045,.055,.5,6),base);grip.rotation.x=Math.PI/2;root.add(grip);const len=w.id==='scythe'?1.35:w.id==='hammer'?.9:1.12,blade=new THREE.Mesh(w.id==='hammer'?new THREE.BoxGeometry(.48,.28,.3):new THREE.BoxGeometry(.08,.09,len),w.id==='hammer'?base:glow);blade.position.z=-len*.55;root.add(blade)}else{const body=new THREE.Mesh(new THREE.BoxGeometry(.23,.2,.78),base);body.position.z=-.3;root.add(body);const barrel=new THREE.Mesh(new THREE.CylinderGeometry(.035,.05,.6,6),glow);barrel.rotation.x=Math.PI/2;barrel.position.z=-.84;root.add(barrel)}root.position.set(.5,.83,.12);root.rotation.y=Math.PI;weaponRig.add(root)}
function clearGroup(g){while(g.children.length){const o=g.children.pop();o.traverse?.(n=>{n.geometry?.dispose();if(Array.isArray(n.material))n.material.forEach(m=>m.dispose());else n.material?.dispose()})}}
function buildRoom(){clearGroup(world);clearGroup(enemyGroup);clearGroup(bulletGroup);clearGroup(pickupGroup);clearGroup(fxGroup);enemies=[];bullets=[];enemyBullets=[];pickups=[];chests=[];shopItems=[];walls=[];orbitals=[];roomClear=false;roomInFloor=room%12;isBoss=roomInFloor===11;isShop=!isBoss&&roomInFloor>0&&roomInFloor%4===3;floor=Math.floor(room/12)+1;difficulty=1+floor*.4+roomInFloor*.11;mapHalf=24+Math.min(4,floor);player.mesh.position.set(0,0,mapHalf-6);makeRoom();if(isShop)makeShop();else if(isBoss)spawnBoss();else spawnWave();notice(`DECK ${floor} · ROOM ${roomInFloor+1}/12`)}
function makeRoom(){const floorMat=mat(0x7c838c,.88,.05),wallMat=mat(0xa7abb1,.76,.06);const fm=new THREE.Mesh(new THREE.PlaneGeometry(mapHalf*2,mapHalf*2),floorMat);fm.rotation.x=-Math.PI/2;fm.receiveShadow=true;world.add(fm);const addWall=(x,z,w,d,h=4.8)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),wallMat);m.position.set(x,h/2,z);m.castShadow=m.receiveShadow=true;world.add(m);walls.push({x,z,w,d,h})};addWall(0,mapHalf,mapHalf*2,1);addWall(-mapHalf,0,1,mapHalf*2);addWall(mapHalf,0,1,mapHalf*2);addWall(-mapHalf*.62,-mapHalf,mapHalf*.65,1);addWall(mapHalf*.62,-mapHalf,mapHalf*.65,1);const variant=room%3;if(variant===1){addWall(-8,0,1.4,8);addWall(8,0,1.4,8)}else if(variant===2){for(const x of [-8,8])for(const z of [-6,6])addWall(x,z,1.4,1.4)}for(const x of [-mapHalf+4,mapHalf-4])for(const z of [-mapHalf+5,0,mapHalf-5]){const lamp=new THREE.Mesh(new THREE.BoxGeometry(.8,.1,.35),new THREE.MeshBasicMaterial({color:0xffffff}));lamp.position.set(x,3.8,z);world.add(lamp)}}
function enemyModel(def,boss=false){const g=new THREE.Group(),main=mat(def.color,.5,.12),dark=mat(0x333944,.76,.08);const body=new THREE.Mesh(new THREE.CapsuleGeometry(boss?1.05:def.r*.7,boss?1.2:.62,4,7),main);body.position.y=boss?1.9:1.0;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(boss?.62:.38,10,8),main);head.position.y=boss?3.15:1.82;g.add(head);for(const x of [-.15,.15]){const eye=new THREE.Mesh(new THREE.SphereGeometry(boss?.11:.075,7,5),new THREE.MeshBasicMaterial({color:0xffffff}));eye.scale.z=.55;eye.position.set(x*(boss?2:1),head.position.y+.05,boss?.58:.35);g.add(eye);const p=new THREE.Mesh(new THREE.SphereGeometry(boss?.045:.028,6,4),new THREE.MeshBasicMaterial({color:0x11151c}));p.position.set(x*(boss?2:1),head.position.y+.05,boss?.64:.39);g.add(p)}const sh=new THREE.Mesh(new THREE.BoxGeometry(boss?2.2:1.1,.16,.44),dark);sh.position.set(0,body.position.y+.45,0);g.add(sh);return g}
function spawnEnemy(def=pick(POOL)){const scale=difficulty*(1+.06*floor),e={...def,hp:def.hp*scale,maxHp:def.hp*scale,damage:def.damage*(1+.08*floor),mesh:enemyModel(def),cd:rand(.3,1.2),t:rand(0,5),dead:false,flash:0};let tries=0;do{e.mesh.position.set(rand(-mapHalf+3,mapHalf-3),0,rand(-mapHalf+5,4));tries++}while(collidesWalls(e.mesh.position,e.r+.2)&&tries<20);enemyGroup.add(e.mesh);enemies.push(e)}
function spawnWave(){const n=Math.min(11,5+Math.floor(roomInFloor*.35)+Math.floor(floor*.45));for(let i=0;i<n;i++)spawnEnemy(POOL[(Math.random()*Math.min(POOL.length,8+floor*2))|0]);if(Math.random()<.5)spawnChest(rand(-10,10),rand(-5,8))}
function spawnBoss(){const d=BOSSES[(floor-1)%BOSSES.length],e={...d,hp:d.hp*difficulty,maxHp:d.hp*difficulty,r:1.6,mesh:enemyModel({...d,r:1.6},true),cd:.8,t:0,boss:true,dead:false,damage:36+floor*7,flash:0};e.mesh.position.set(0,0,-mapHalf+8);enemyGroup.add(e.mesh);enemies.push(e);notice(d.name,2)}
function spawnChest(x,z){const g=new THREE.Group(),b=new THREE.Mesh(new THREE.BoxGeometry(1.7,.75,1.1),mat(0x66576d,.55,.22)),lid=new THREE.Mesh(new THREE.BoxGeometry(1.75,.24,1.12),mat(0x444b56,.4,.45));b.position.y=.42;lid.position.y=.91;g.add(b,lid);g.position.set(x,0,z);world.add(g);chests.push({mesh:g,opened:false})}
function makeShop(){roomClear=true;for(const x of [-7,0,7]){const w=pick(WEAPONS),cost=Math.round(32+(WEAPONS.indexOf(w)+1)*6+floor*7),ped=new THREE.Mesh(new THREE.CylinderGeometry(.9,1,.6,10),mat(0x555d67,.5,.35));ped.position.set(x,.3,1);world.add(ped);shopItems.push({x,z:1,w,cost,bought:false,ped})}}
function weaponHTML(w){const r=RARITY[w.rarity];return `<span class="rarity" style="color:${r.color}">${r.label||w.rarity}</span><h3>${w.name}</h3><b>${w.type}</b><p>${w.desc.replace(/aim assist/gi,'precision')}</p>`}
function openChest(c){if(c.opened)return;c.opened=true;world.remove(c.mesh);releaseMouse();const opts=[pick(WEAPONS),pick(WEAPONS),pick(WEAPONS)];showChoices('Cache',opts.map(w=>({label:weaponHTML(w),action:()=>{replaceWeapon(w.id);closeModal()}})),true)}
function replaceWeapon(id){player.slots[player.slot]={id,ammo:wmap[id].mag??0,reload:0,cd:0};refreshHeldWeapon()}
function showChoices(title,items,skip=false){releaseMouse();modal.classList.add('show');modal.innerHTML=`<div class="card"><h2>${title}</h2><div class="grid">${items.map((it,i)=>`<button class="choice" data-i="${i}">${it.label}</button>`).join('')}${skip?'<button class="choice" data-skip><h3>Skip</h3></button>':''}</div></div>`;modal.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>items[+b.dataset.i].action());modal.querySelector('[data-skip]')?.addEventListener('click',()=>closeModal())}
function closeModal(relock=true){modal.classList.remove('show');if(relock)setTimeout(grabMouse,0)}
function interact(){for(const c of chests)if(!c.opened&&c.mesh.position.distanceTo(player.mesh.position)<3)return openChest(c);if(isShop){for(const it of shopItems){const d=Math.hypot(player.mesh.position.x-it.x,player.mesh.position.z-it.z);if(d<2.5&&!it.bought){if(player.coins<it.cost)return notice('Yetersiz kredi');player.coins-=it.cost;it.bought=true;replaceWeapon(it.w.id);return}}}}
function nextRoom(){room++;buildRoom()}
function reload(){const s=player.slots[player.slot],w=currentWeapon();if(w.kind==='melee'||w.kind==='orbital'||s.reload>0)return;s.reload=w.reload}
function collidesWalls(p,r=.6){return walls.some(w=>Math.abs(p.x-w.x)<w.w/2+r&&Math.abs(p.z-w.z)<w.d/2+r)}function resolveWall(p,w,r){if(Math.abs(p.x-w.x)<w.w/2+r&&Math.abs(p.z-w.z)<w.d/2+r){const dx=w.w/2+r-Math.abs(p.x-w.x),dz=w.d/2+r-Math.abs(p.z-w.z);if(dx<dz)p.x+=Math.sign(p.x-w.x||1)*dx;else p.z+=Math.sign(p.z-w.z||1)*dz}}function segmentHitsWall(a,b,r=.06){const dist=a.distanceTo(b),steps=Math.max(2,Math.ceil(dist/.8));for(const w of walls)for(let i=1;i<=steps;i++){const p=tmpA.copy(a).lerp(b,i/steps);if(Math.abs(p.x-w.x)<w.w/2+r&&Math.abs(p.z-w.z)<w.d/2+r&&p.y<w.h+.25)return true}return false}
function findVisibleLockTarget(max=52){let best=null,bestScore=Infinity;for(const e of enemies)if(!e.dead){const aim=e.mesh.position.clone().add(new THREE.Vector3(0,e.boss?2:1.35,0)),d=aim.distanceTo(camera.position);if(d>max)continue;const ndc=aim.clone().project(camera);if(ndc.z<0||ndc.z>1||Math.abs(ndc.x)>1||Math.abs(ndc.y)>1)continue;if(segmentHitsWall(camera.position,aim,.04))continue;const score=Math.hypot(ndc.x,ndc.y)*18+d*.35;if(score<bestScore){bestScore=score;best=e}}return best}
function isTargetVisible(e){if(!e||e.dead)return false;const aim=e.mesh.position.clone().add(new THREE.Vector3(0,e.boss?2:1.35,0)),ndc=aim.clone().project(camera);return ndc.z>=0&&ndc.z<=1&&Math.abs(ndc.x)<=1&&Math.abs(ndc.y)<=1&&!segmentHitsWall(camera.position,aim,.04)}
function cameraForward(){return new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(-pitch),Math.cos(yaw)*Math.cos(pitch)).normalize()}
function movePlayer(dt){const forward=new THREE.Vector3(Math.sin(yaw),0,Math.cos(yaw)),right=new THREE.Vector3(-forward.z,0,forward.x),dir=new THREE.Vector3();if(keys.KeyW)dir.add(forward);if(keys.KeyS)dir.sub(forward);if(keys.KeyD)dir.add(right);if(keys.KeyA)dir.sub(right);if(dir.lengthSq())dir.normalize();if(keys.ShiftLeft&&player.dash<=0){player.dash=player.dashMax;player.ifr=.22;dir.multiplyScalar(2.6)}player.dash=Math.max(0,player.dash-dt);player.mesh.position.addScaledVector(dir,player.speed*dt);player.mesh.position.x=clamp(player.mesh.position.x,-mapHalf+1.4,mapHalf-1.4);player.mesh.position.z=clamp(player.mesh.position.z,-mapHalf+1.4,mapHalf-1.4);for(const w of walls)resolveWall(player.mesh.position,w,.58);if(keys.Space&&player.onGround){player.yVel=8.5;player.onGround=false}player.yVel-=21*dt;player.mesh.position.y+=player.yVel*dt;if(player.mesh.position.y<=0){player.mesh.position.y=0;player.yVel=0;player.onGround=true}if(mouse.right&&lockedTarget&&!lockedTarget.dead){const v=lockedTarget.mesh.position.clone().sub(player.mesh.position);player.mesh.rotation.y=Math.atan2(v.x,v.z)}else if(mouse.left)player.mesh.rotation.y=yaw;else if(dir.lengthSq()){const desired=Math.atan2(dir.x,dir.z),delta=Math.atan2(Math.sin(desired-player.mesh.rotation.y),Math.cos(desired-player.mesh.rotation.y));player.mesh.rotation.y+=delta*clamp(dt*12,0,1)}if(roomClear&&player.mesh.position.z<-mapHalf+1.8)nextRoom()}
function updateCamera(dt){const target=player.mesh.position.clone().add(new THREE.Vector3(0,1.25,0)),forward=cameraForward(),flatForward=new THREE.Vector3(forward.x,0,forward.z).normalize(),right=new THREE.Vector3(-flatForward.z,0,flatForward.x),dist=mouse.right?6.1:8.8,up=mouse.right?2.65:3.25;let desired=target.clone().addScaledVector(flatForward,-dist).add(new THREE.Vector3(0,up,0));desired.addScaledVector(right,mouse.right?.9:0);let safe=desired.clone();if(segmentHitsWall(target,desired,.16)){for(let t=.88;t>.14;t-=.07){const p=target.clone().lerp(desired,t);if(!segmentHitsWall(target,p,.14)){safe=p;break}}}if(shake>0){safe.x+=rand(-shake,shake);safe.y+=rand(-shake*.55,shake*.55);safe.z+=rand(-shake,shake);shake*=Math.pow(.03,dt);if(shake<.005)shake=0}camera.position.lerp(safe,1-Math.pow(.0008,dt));let look=target.clone().add(forward.clone().multiplyScalar(16));look.y+=mouse.right?.35:1;if(mouse.right&&lockedTarget&&!lockedTarget.dead){const enemyAim=lockedTarget.mesh.position.clone().add(new THREE.Vector3(0,lockedTarget.boss?1.8:1.15,0));look.lerp(enemyAim,.62)}camera.lookAt(look)}
function aimDirection(){if(mouse.right&&lockedTarget&&!lockedTarget.dead){const origin=player.mesh.position.clone().add(new THREE.Vector3(0,1.25,0));return lockedTarget.mesh.position.clone().add(new THREE.Vector3(0,lockedTarget.boss?1.8:1.1,0)).sub(origin).normalize()}const ndc=new THREE.Vector3(mouse.right?.12:0,0,.5).unproject(camera);return ndc.sub(camera.position).normalize()}
function fire(){const s=player.slots[player.slot],w=currentWeapon();if(s.cd>0||s.reload>0)return;s.cd=1/(w.rate*player.attackSpeed);if(w.kind==='melee')return melee(w);if(w.kind==='orbital')return spawnOrbital(w);if(s.ammo<=0)return reload();s.ammo--;const dir=aimDirection(),origin=player.mesh.position.clone().add(new THREE.Vector3(.48,1.15,0)).addScaledVector(dir,.65);if(w.kind==='beam')return beamShot(origin,dir,w);for(let i=0;i<(w.pellets||1);i++){const d=dir.clone();if(w.spread){d.x+=rand(-w.spread,w.spread);d.y+=rand(-w.spread*.3,w.spread*.3);d.z+=rand(-w.spread,w.spread);d.normalize()}spawnBullet(origin,d,w)}}
function spawnBullet(origin,dir,w){const m=new THREE.Mesh(new THREE.SphereGeometry(w.kind==='grenade'?.18:.09,7,5),new THREE.MeshBasicMaterial({color:RARITY[w.rarity]?.color||0xffffff}));m.position.copy(origin);bulletGroup.add(m);bullets.push({mesh:m,vel:dir.clone().multiplyScalar(w.speed),life:(w.range||60)/Math.max(1,w.speed),w,damage:w.damage*player.damage,pierce:w.pierce||0})}
function beamShot(origin,dir,w){let nearest=null,nd=w.range;for(const e of enemies)if(!e.dead){const to=e.mesh.position.clone().add(new THREE.Vector3(0,1,0)).sub(origin),proj=to.dot(dir);if(proj>0&&proj<nd&&to.clone().sub(dir.clone().multiplyScalar(proj)).length()<e.r+.7&&!segmentHitsWall(origin,e.mesh.position.clone().add(new THREE.Vector3(0,1,0)))){nearest=e;nd=proj}}if(nearest)hitEnemy(nearest,w.damage*player.damage*(nearest.boss?player.bossDamage:1))}
function spawnOrbital(w){for(let i=0;i<3;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(.18,7,5),new THREE.MeshBasicMaterial({color:RARITY[w.rarity]?.color||0xffffff}));bulletGroup.add(m);orbitals.push({mesh:m,angle:i*Math.PI*2/3,life:7,damage:w.damage})}}
function melee(w){const forward=new THREE.Vector3(Math.sin(player.mesh.rotation.y),0,Math.cos(player.mesh.rotation.y)),origin=player.mesh.position.clone(),range=(w.range||3)*1.4,maxAngle=(w.arc||1.8)/2+.25;let hit=false;for(const e of enemies)if(!e.dead){const flat=e.mesh.position.clone().sub(origin);flat.y=0;const dist=flat.length();if(dist<=range+e.r&&Math.acos(clamp(flat.normalize().dot(forward),-1,1))<=maxAngle&&!segmentHitsWall(origin.clone().add(new THREE.Vector3(0,1,0)),e.mesh.position.clone().add(new THREE.Vector3(0,1,0)))){hitEnemy(e,w.damage*player.damage*player.melee*(e.boss?player.bossDamage:1));hit=true}}if(hit){shake=Math.max(shake,.06);hitStop=Math.max(hitStop,.035)}}
function flashEnemy(e){e.flash=.07;e.mesh.traverse(n=>{if(n.material&&n.material.color&&!n.userData.oldColor){n.userData.oldColor=n.material.color.getHex();n.material.color.setHex(0xffffff)}})}function restoreEnemy(e){if(e.flash>0)return;e.mesh.traverse(n=>{if(n.material&&n.userData.oldColor!==undefined){n.material.color.setHex(n.userData.oldColor);delete n.userData.oldColor}})}
function hitEnemy(e,d){e.hp-=d;flashEnemy(e);shake=Math.max(shake,e.boss?.045:.025);hitStop=Math.max(hitStop,e.boss?.022:.012);if(e.hp<=0&&!e.dead){e.dead=true;const pos=e.mesh.position.clone();enemyGroup.remove(e.mesh);player.xp+=e.xp||45;spawnCoin(pos,Math.max(3,Math.round((e.xp||40)/9)));player.hp=Math.min(player.maxHp,player.hp+player.killHeal);checkLevel()}}
function spawnCoin(pos,v){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(.16,0),new THREE.MeshBasicMaterial({color:0xffd25a}));m.position.copy(pos).add(new THREE.Vector3(0,.4,0));pickupGroup.add(m);pickups.push({mesh:m,v})}
function checkLevel(){while(player.xp>=player.nextXp){player.xp-=player.nextXp;player.level++;player.nextXp=Math.floor(player.nextXp*1.22+25);const opts=[...UPGRADES].filter(u=>!/aim assist/i.test(u.name+u.desc)).sort(()=>Math.random()-.5).slice(0,3);showChoices(`Level ${player.level}`,opts.map(u=>({label:`<h3>${u.name}</h3><p>${u.desc.replace(/aim assist/gi,'precision')}</p>`,action:()=>{u.apply(player);closeModal()}})))}}
function enemyShoot(e,dir,speed=12,count=1,spread=.12){for(let i=0;i<count;i++){const d=dir.clone();if(count>1){const a=(i-(count-1)/2)*spread,c=Math.cos(a),s=Math.sin(a),x=d.x*c-d.z*s,z=d.x*s+d.z*c;d.x=x;d.z=z}const m=new THREE.Mesh(new THREE.SphereGeometry(.13,7,5),new THREE.MeshBasicMaterial({color:e.color||0xff5a75}));m.position.copy(e.mesh.position).add(new THREE.Vector3(0,1.1,0));bulletGroup.add(m);enemyBullets.push({mesh:m,vel:d.normalize().multiplyScalar(speed),life:6,damage:e.damage||24})}}
function ring(e,n=14,s=9,o=0){for(let i=0;i<n;i++){const a=o+i*Math.PI*2/n;enemyShoot(e,new THREE.Vector3(Math.sin(a),0,Math.cos(a)),s)}}
function updateEnemies(dt){for(const e of enemies)if(!e.dead){if(e.flash>0){e.flash-=dt;if(e.flash<=0)restoreEnemy(e)}e.t+=dt;e.cd-=dt;const to=player.mesh.position.clone().sub(e.mesh.position),dist=to.length(),dir=to.normalize(),spd=e.speed*Math.min(1.8,1+.08*floor),old=e.mesh.position.clone();if(e.boss)bossAI(e,dir,dt);else if(e.ai==='chase')e.mesh.position.addScaledVector(dir,spd*dt);else if(e.ai==='orbit'){const side=new THREE.Vector3(-dir.z,0,dir.x);e.mesh.position.addScaledVector(side,spd*dt);if(e.cd<=0){enemyShoot(e,dir,13);e.cd=1.1/difficulty}}else if(e.ai==='shooter'||e.ai==='sniper'){if(dist>12)e.mesh.position.addScaledVector(dir,spd*.5*dt);if(e.cd<=0){enemyShoot(e,dir,e.ai==='sniper'?19:13);e.cd=(e.ai==='sniper'?1.8:1)/Math.min(2,difficulty)}}else if(e.ai==='radial'&&e.cd<=0){ring(e,12+floor,9+floor*.25,e.t);e.cd=1.65/Math.min(2,difficulty)}else if(e.ai==='charge'){if(e.cd<=0){e.charge=.55;e.cd=2.1}if(e.charge>0){e.mesh.position.addScaledVector(dir,spd*3.2*dt);e.charge-=dt}}else if(e.ai==='spiral'&&e.cd<=0){for(let i=0;i<5;i++){const a=e.t+i*Math.PI*2/5;enemyShoot(e,new THREE.Vector3(Math.sin(a),0,Math.cos(a)),10)}e.cd=.34/Math.min(2,difficulty)}else if(e.ai==='rings'&&e.cd<=0){ring(e,18,9,e.t);e.cd=1.55/Math.min(2,difficulty)}else if(e.ai==='burst'&&e.cd<=0){enemyShoot(e,dir,14,5,.11);e.cd=.95/Math.min(2,difficulty)}else if(e.ai==='blink'&&e.cd<=0){const np=player.mesh.position.clone().add(new THREE.Vector3(rand(-9,9),0,rand(-9,9)));if(!collidesWalls(np,e.r))e.mesh.position.copy(np);e.cd=1.9}else if(e.ai==='satellite'&&e.cd<=0){ring(e,8,8,e.t);enemyShoot(e,dir,14);e.cd=.9/Math.min(2,difficulty)}else if(e.ai==='fan'&&e.cd<=0){enemyShoot(e,dir,13,7,.22);e.cd=1.1/Math.min(2,difficulty)}for(const w of walls)resolveWall(e.mesh.position,w,e.r*.7);if(segmentHitsWall(old,e.mesh.position,e.r*.2))e.mesh.position.copy(old);if(dist<e.r+.7)hurtPlayer((e.damage||24)*dt*1.8);e.mesh.rotation.y=Math.atan2(dir.x,dir.z)}}
function bossAI(e,dir,dt){const phase=1+Math.floor((1-e.hp/e.maxHp)*3);if(e.cd<=0){ring(e,16+phase*4,10+phase,e.t);enemyShoot(e,dir,16,3+phase*2,.11);e.cd=Math.max(.6,1.65-phase*.18)}e.mesh.position.addScaledVector(new THREE.Vector3(-dir.z,0,dir.x),1.4*dt);for(const w of walls)resolveWall(e.mesh.position,w,1.2)}
function updateBullets(dt){for(const b of bullets){const old=b.mesh.position.clone();if(b.w.kind==='homing'){const e=findNearestFrom(b.mesh.position,45);if(e){const desired=e.mesh.position.clone().add(new THREE.Vector3(0,1,0)).sub(b.mesh.position).normalize().multiplyScalar(b.w.speed);b.vel.lerp(desired,clamp(b.w.turn*dt,0,1))}}b.mesh.position.addScaledVector(b.vel,dt);b.life-=dt;if(segmentHitsWall(old,b.mesh.position,.1)){b.life=0;continue}for(const e of enemies)if(!e.dead&&b.mesh.position.distanceTo(e.mesh.position.clone().add(new THREE.Vector3(0,1,0)))<e.r+.32){hitEnemy(e,b.damage*(e.boss?player.bossDamage:1));if(b.pierce-->0){}else{b.life=0;break}}}for(const b of enemyBullets){const old=b.mesh.position.clone();b.mesh.position.addScaledVector(b.vel,dt);b.life-=dt;if(segmentHitsWall(old,b.mesh.position,.11)){b.life=0;continue}if(b.mesh.position.distanceTo(player.mesh.position.clone().add(new THREE.Vector3(0,1,0)))<.68){hurtPlayer(b.damage);b.life=0}}for(const o of orbitals){o.angle+=dt*3.6;o.life-=dt;o.mesh.position.copy(player.mesh.position).add(new THREE.Vector3(Math.cos(o.angle)*2.35,1.35,Math.sin(o.angle)*2.35));for(const e of enemies)if(!e.dead&&o.mesh.position.distanceTo(e.mesh.position)<e.r+.4)hitEnemy(e,o.damage*dt*3.3)}bullets=bullets.filter(b=>{if(b.life<=0){bulletGroup.remove(b.mesh);return false}return true});enemyBullets=enemyBullets.filter(b=>{if(b.life<=0){bulletGroup.remove(b.mesh);return false}return true});orbitals=orbitals.filter(o=>{if(o.life<=0){bulletGroup.remove(o.mesh);return false}return true})}
function findNearestFrom(pos,max){let best=null,bd=max;for(const e of enemies)if(!e.dead){const d=e.mesh.position.distanceTo(pos);if(d<bd){bd=d;best=e}}return best}
function hurtPlayer(d){if(player.ifr>0)return;player.hp-=d;player.ifr=.18;shake=Math.max(shake,.22);if(player.hp<=0)gameOver()}
function gameOver(){releaseMouse();modal.classList.add('show');modal.innerHTML=`<div class="card death"><h1>SYSTEM FAILURE</h1><button id="restart" class="choice"><h3>RESTART</h3></button></div>`;$('#restart').onclick=()=>location.reload()}
function updatePickups(dt){for(const p of pickups){p.mesh.rotation.y+=dt*3;const to=player.mesh.position.clone().add(new THREE.Vector3(0,.5,0)).sub(p.mesh.position),d=to.length(),radius=7.5*player.pickup;if(d<radius)p.mesh.position.addScaledVector(to.normalize(),dt*(8+radius-d));if(d<.75){player.coins+=p.v;p.dead=true;pickupGroup.remove(p.mesh)}}pickups=pickups.filter(p=>!p.dead)}
function drawHud(){const w=currentWeapon(),s=player.slots[player.slot],meleeCd=w.kind==='melee'?clamp(1-s.cd*w.rate*player.attackSpeed,0,1):1;hud.innerHTML=`<div class="topbar"><div><b>DECK ${floor} · ROOM ${roomInFloor+1}/12</b></div><div class="credits">◈ ${player.coins} CR</div></div><div class="health"><span>HP ${Math.ceil(player.hp)}/${Math.ceil(player.maxHp)}</span><i style="width:${clamp(player.hp/player.maxHp*100,0,100)}%"></i></div><div class="reticle ${mouse.right&&lockedTarget?'locked':''}"></div><div class="slots">${player.slots.map((q,i)=>{const ww=wmap[q.id];return`<div class="slot ${i===player.slot?'active':''}"><small>${i+1}</small><b style="color:${RARITY[ww.rarity].color}">${ww.name}</b><span>${ww.type}</span></div>`}).join('')}</div><div class="weaponinfo"><b>${w.name}</b><span>${w.kind==='melee'?'MELEE':`${s.reload>0?'RELOADING':s.ammo+'/'+(w.mag||0)}`}</span>${w.kind==='melee'?`<em><i style="width:${meleeCd*100}%"></i></em>`:''}</div><div class="controls">WASD move · Mouse free camera · LMB attack · RMB visible-target lock · Space jump · Shift dash</div>`}
function notice(t,time=1.4){const n=document.createElement('div');n.className='notice';n.textContent=t;document.body.appendChild(n);setTimeout(()=>n.remove(),time*1000)}
function update(dt){if(!player||modal.classList.contains('show'))return;if(hitStop>0){hitStop-=dt;updateCamera(dt*.2);drawHud();return}for(const s of player.slots){s.cd=Math.max(0,s.cd-dt);if(s.reload>0){s.reload-=dt;if(s.reload<=0)s.ammo=wmap[s.id].mag??0}}player.ifr=Math.max(0,player.ifr-dt);if(mouse.right){lockRefresh-=dt;if(lockRefresh<=0){if(!lockedTarget||lockedTarget.dead||!isTargetVisible(lockedTarget))lockedTarget=findVisibleLockTarget(52);lockRefresh=.08}}movePlayer(dt);if(mouse.left)fire();updateCamera(dt);updateBullets(dt);updateEnemies(dt);updatePickups(dt);if(!roomClear&&enemies.every(e=>e.dead)){roomClear=true;notice(isBoss?'BOSS DOWN · EXIT OPEN':'ROOM CLEAR · EXIT OPEN');if(!isBoss&&Math.random()<.32)spawnChest(rand(-8,8),rand(-1,9))}drawHud()}
function animate(){requestAnimationFrame(animate);const dt=Math.min(.033,clock.getDelta());if(modal.classList.contains('show'))return;update(dt);renderer.render(scene,camera)}
init();