import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {CLASSES,RARITY,WEAPONS,ENEMIES,BOSSES,UPGRADES,ROOM_THEMES} from './data.js';

const $=s=>document.querySelector(s),hud=$('#hud'),modal=$('#modal');
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),pick=a=>a[(Math.random()*a.length)|0];
const wmap=Object.fromEntries(WEAPONS.map(w=>[w.id,w]));
let scene,camera,renderer,clock,player,world,enemyGroup,bulletGroup,pickupGroup,fxGroup,weaponRig;
let enemies=[],bullets=[],enemyBullets=[],pickups=[],chests=[],shopItems=[],walls=[],orbitals=[];
let keys={},mouse={left:false,right:false},yaw=0,pitch=-.22,lockedTarget=null;
let floor=1,room=0,sector=1,roomClear=false,isShop=false,isBoss=false,difficulty=1,mapHalf=30,currentTheme;
const UP=new THREE.Vector3(0,1,0),tmpA=new THREE.Vector3(),tmpB=new THREE.Vector3(),tmpC=new THREE.Vector3();

function mat(color,rough=.65,metal=.15,emissive=0){return new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal,emissive,emissiveIntensity:emissive?0.7:0})}
function init(){
 scene=new THREE.Scene();scene.background=new THREE.Color(0x151922);scene.fog=new THREE.FogExp2(0x242a36,.0048);
 camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.1,240);
 renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.55;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;$('#game').appendChild(renderer.domElement);
 scene.add(new THREE.HemisphereLight(0xeaf3ff,0x52606f,2.25));const key=new THREE.DirectionalLight(0xffffff,3.4);key.position.set(14,24,10);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-38;key.shadow.camera.right=38;key.shadow.camera.top=38;key.shadow.camera.bottom=-38;key.shadow.bias=-.0004;scene.add(key);const fill=new THREE.DirectionalLight(0xbfd7ff,1.25);fill.position.set(-12,10,-8);scene.add(fill);
 world=new THREE.Group();enemyGroup=new THREE.Group();bulletGroup=new THREE.Group();pickupGroup=new THREE.Group();fxGroup=new THREE.Group();scene.add(world,enemyGroup,bulletGroup,pickupGroup,fxGroup);
 clock=new THREE.Clock();bind();chooseClass();animate();
}
function bind(){
 addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
 addEventListener('keydown',e=>{keys[e.code]=true;if(['Digit1','Digit2','Digit3'].includes(e.code)&&player){player.slot=+e.code.at(-1)-1;refreshHeldWeapon()}if(e.code==='KeyE'&&player)interact();if(e.code==='KeyR'&&player)reload()});addEventListener('keyup',e=>keys[e.code]=false);
 renderer.domElement.addEventListener('mousedown',e=>{if(e.button===0)mouse.left=true;if(e.button===2){mouse.right=true;lockedTarget=findNearestEnemy(45)}});addEventListener('mouseup',e=>{if(e.button===0)mouse.left=false;if(e.button===2){mouse.right=false;lockedTarget=null}});renderer.domElement.oncontextmenu=e=>e.preventDefault();
 renderer.domElement.addEventListener('click',()=>{if(!modal.classList.contains('show'))renderer.domElement.requestPointerLock?.()});document.addEventListener('mousemove',e=>{if(document.pointerLockElement===renderer.domElement&&!mouse.right){yaw-=e.movementX*.0021;pitch=clamp(pitch-e.movementY*.00165,-.58,.18)}})
}
function releaseMouse(){if(document.pointerLockElement)document.exitPointerLock?.()}function grabMouse(){if(!modal.classList.contains('show'))renderer.domElement.requestPointerLock?.()}
function chooseClass(){releaseMouse();modal.classList.add('show');modal.innerHTML=`<div class="card hero"><div class="eyebrow">OPERATIVE SELECT</div><h1>Class seç</h1><p class="muted">Başlangıç üçlüsü, hız, dayanıklılık ve renk değişir.</p><div class="grid">${Object.entries(CLASSES).map(([id,c])=>`<button class="choice" data-class="${id}"><span class="classdot" style="background:#${c.color.toString(16).padStart(6,'0')}"></span><h3 style="color:#${c.color.toString(16).padStart(6,'0')}">${c.name}</h3><p>${c.desc}</p><small>HP ${c.hp} · SPD ${c.speed}</small></button>`).join('')}</div></div>`;modal.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>startGame(b.dataset.class))}
function startGame(id){const c=CLASSES[id];player={classId:id,class:c,mesh:makePlayer(c.color),yVel:0,onGround:true,hp:c.hp,maxHp:c.hp,speed:c.speed,damage:c.damage,crit:c.crit||.08,melee:c.melee||1,attackSpeed:1,bossDamage:1,pickup:1,killHeal:0,coins:0,xp:0,level:1,nextXp:90,slots:c.slots.map(id=>({id,ammo:wmap[id].mag??0,reload:0,cd:0})),slot:0,dash:0,dashMax:.9,ifr:0};scene.add(player.mesh);weaponRig=new THREE.Group();player.mesh.add(weaponRig);refreshHeldWeapon();closeModal(false);buildRoom()}
function makePlayer(color){const g=new THREE.Group(),armor=mat(color,.42,.35,new THREE.Color(color).multiplyScalar(.05).getHex()),dark=mat(0x202632,.72,.22),face=mat(0x596273,.52,.28);const body=new THREE.Mesh(new THREE.CapsuleGeometry(.58,1.0,5,10),armor);body.position.y=1.35;body.castShadow=true;g.add(body);const chest=new THREE.Mesh(new THREE.BoxGeometry(.9,.2,.62),dark);chest.position.set(0,1.62,.18);g.add(chest);const head=new THREE.Mesh(new THREE.SphereGeometry(.43,16,12),face);head.position.set(0,2.29,0);head.castShadow=true;g.add(head);for(const x of [-.145,.145]){const white=new THREE.Mesh(new THREE.SphereGeometry(.09,10,7),new THREE.MeshBasicMaterial({color:0xf8fbff}));white.scale.set(1,1.15,.5);white.position.set(x,2.35,.395);g.add(white);const pupil=new THREE.Mesh(new THREE.SphereGeometry(.037,8,6),new THREE.MeshBasicMaterial({color:0x101622}));pupil.position.set(x,2.35,.442);g.add(pupil)}const mouth=new THREE.Mesh(new THREE.TorusGeometry(.09,.012,5,10,Math.PI),new THREE.MeshBasicMaterial({color:0x20242d}));mouth.position.set(0,2.16,.42);mouth.rotation.z=Math.PI;g.add(mouth);const cape=new THREE.Mesh(new THREE.BoxGeometry(.86,1.18,.07),dark);cape.position.set(0,1.44,-.55);g.add(cape);return g}
function currentWeapon(){return wmap[player.slots[player.slot].id]}
function refreshHeldWeapon(){if(!weaponRig||!player)return;weaponRig.clear();const w=currentWeapon(),base=mat(0x29303d,.35,.72),glow=new THREE.MeshBasicMaterial({color:RARITY[w.rarity]?.color||0xffffff}),root=new THREE.Group();if(w.kind==='melee'){const grip=new THREE.Mesh(new THREE.CylinderGeometry(.045,.055,.52,8),base);grip.rotation.x=Math.PI/2;root.add(grip);const len=w.id==='moon_scythe'?1.35:w.id==='saintbreaker'?.9:1.15,blade=new THREE.Mesh(w.id==='saintbreaker'?new THREE.BoxGeometry(.5,.3,.32):new THREE.BoxGeometry(.08,.1,len),w.id==='saintbreaker'?base:glow);blade.position.z=-len*.57;root.add(blade)}else{const body=new THREE.Mesh(new THREE.BoxGeometry(.22,.2,.8),base);body.position.z=-.34;root.add(body);const barrel=new THREE.Mesh(new THREE.CylinderGeometry(.04,.055,.62,8),glow);barrel.rotation.x=Math.PI/2;barrel.position.z=-.88;root.add(barrel)}root.position.set(.62,1.5,.12);root.rotation.y=Math.PI;weaponRig.add(root)}
function clearGroup(g){while(g.children.length){const o=g.children.pop();o.traverse?.(n=>{n.geometry?.dispose();if(Array.isArray(n.material))n.material.forEach(m=>m.dispose());else n.material?.dispose()})}}
function buildRoom(){clearGroup(world);clearGroup(enemyGroup);clearGroup(bulletGroup);clearGroup(pickupGroup);clearGroup(fxGroup);enemies=[];bullets=[];enemyBullets=[];pickups=[];chests=[];shopItems=[];walls=[];orbitals=[];roomClear=false;sector=Math.floor(room/5)+1;isBoss=room>0&&room%8===7;isShop=!isBoss&&room>0&&room%4===3;difficulty=1+floor*.42+room*.14;mapHalf=30+Math.min(10,floor*2);player.mesh.position.set(0,0,mapHalf-8);currentTheme=pick(ROOM_THEMES);makeRoom(currentTheme);if(isShop)makeShop();else if(isBoss)spawnBoss();else spawnWave();notice(`${currentTheme.name} · DECK ${floor} · SECTOR ${sector} · ROOM ${room+1}`)}
function makeRoom(theme){const floorMat=mat(0x687180,.8,.18),wallMat=mat(0x8a9099,.68,.12);const fm=new THREE.Mesh(new THREE.PlaneGeometry(mapHalf*2,mapHalf*2),floorMat);fm.rotation.x=-Math.PI/2;fm.receiveShadow=true;world.add(fm);const addWall=(x,z,w,d,h=5.4)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),wallMat);m.position.set(x,h/2,z);m.castShadow=m.receiveShadow=true;world.add(m);walls.push({x,z,w,d,h});};addWall(0,-mapHalf,mapHalf*2,1.2);addWall(0,mapHalf,mapHalf*2,1.2);addWall(-mapHalf,0,1.2,mapHalf*2);addWall(mapHalf,0,1.2,mapHalf*2);const divider=(z,gaps=[0])=>{for(let x=-mapHalf+4;x<mapHalf;x+=8){if(gaps.some(g=>Math.abs(x-g)<5))continue;addWall(x,z,7.5,1,4.6)}};divider(-10,[-12,12]);divider(10,[0]);if(theme.shape==='gallery'||theme.shape==='nave')for(const x of [-16,0,16])for(const z of [-19,0,19])addWall(x,z,2.2,2.2,6.6);if(theme.shape==='cloister')for(const x of [-12,12])addWall(x,0,1.1,20,4.2);if(theme.shape==='chapel'){addWall(-10,-2,1,19,5);addWall(10,-2,1,19,5)}if(theme.shape==='atrium')for(let a=0;a<10;a++){const q=a*Math.PI*2/10;addWall(Math.cos(q)*11,Math.sin(q)*11,1.5,1.5,5.5)}if(theme.shape==='hangar')for(const z of [-18,0,18]){addWall(-15,z,8,1,3.5);addWall(15,z,8,1,3.5)}if(theme.shape==='throne'){addWall(0,-18,18,1,6);for(const x of [-10,10])addWall(x,-15,1.4,8,6.5)}for(let i=0;i<10;i++){const strip=new THREE.Mesh(new THREE.BoxGeometry(2.4,.05,.08),new THREE.MeshBasicMaterial({color:i%2?0x8fd3ff:0xffffff}));strip.position.set(rand(-mapHalf+4,mapHalf-4),4.2,rand(-mapHalf+4,mapHalf-4));world.add(strip)}}
function enemyModel(def,boss=false){const g=new THREE.Group(),main=mat(def.color,.48,.2,new THREE.Color(def.color).multiplyScalar(.05).getHex()),dark=mat(0x252b35,.72,.18);const core=new THREE.Mesh(new THREE.CapsuleGeometry(boss?1.15:def.r*.72,boss?1.3:.68,5,9),main);core.position.y=boss?2:1.05;core.castShadow=true;g.add(core);const head=new THREE.Mesh(new THREE.SphereGeometry(boss?.68:.4,14,10),main);head.position.y=boss?3.35:1.9;g.add(head);for(const x of [-.17,.17]){const white=new THREE.Mesh(new THREE.SphereGeometry(boss?.12:.085,8,6),new THREE.MeshBasicMaterial({color:0xffffff}));white.scale.z=.55;white.position.set(x*(boss?2:1),head.position.y+.07,boss?.64:.37);g.add(white);const pupil=new THREE.Mesh(new THREE.SphereGeometry(boss?.05:.032,7,5),new THREE.MeshBasicMaterial({color:0x121722}));pupil.position.set(x*(boss?2:1),head.position.y+.07,boss?.7:.42);g.add(pupil)}const shoulder=new THREE.Mesh(new THREE.BoxGeometry(boss?2.4:1.25,.18,.5),dark);shoulder.position.set(0,core.position.y+.5,.02);g.add(shoulder);return g}
function spawnEnemy(def=pick(ENEMIES)){const scale=difficulty*(1+.08*floor),e={...def,hp:def.hp*scale,maxHp:def.hp*scale,damage:def.damage*(1+.1*floor),mesh:enemyModel(def),cd:rand(.3,1.3),t:rand(0,5),dead:false};let tries=0;do{e.mesh.position.set(rand(-mapHalf+4,mapHalf-4),0,rand(-mapHalf+5,4));tries++}while(collidesWalls(e.mesh.position,e.r+.2)&&tries<20);enemyGroup.add(e.mesh);enemies.push(e)}
function spawnWave(){const n=Math.min(8,3+Math.floor(floor*.65)+Math.floor(room*.2));for(let i=0;i<n;i++)spawnEnemy(ENEMIES[Math.min(ENEMIES.length-1,(Math.random()*(5+floor))|0)]);if(Math.random()<.52)spawnChest(rand(-12,12),rand(-6,9))}
function spawnBoss(){const d=BOSSES[(floor-1)%BOSSES.length],e={...d,hp:d.hp*difficulty,maxHp:d.hp*difficulty,r:1.6,mesh:enemyModel({...d,r:1.6},true),cd:.8,t:0,boss:true,dead:false,damage:34+floor*7};e.mesh.position.set(0,0,-mapHalf+10);enemyGroup.add(e.mesh);enemies.push(e);notice(d.name,2.4)}
function spawnChest(x,z){const g=new THREE.Group(),b=new THREE.Mesh(new THREE.BoxGeometry(1.8,.85,1.15),mat(0x5d4e67,.5,.28)),lid=new THREE.Mesh(new THREE.BoxGeometry(1.85,.28,1.18),mat(0x303845,.35,.55));b.position.y=.48;lid.position.y=1.02;g.add(b,lid);g.position.set(x,0,z);world.add(g);chests.push({mesh:g,opened:false})}
function makeShop(){roomClear=true;for(const x of [-8,0,8]){const w=pick(WEAPONS),cost=Math.round(32+(WEAPONS.indexOf(w)+1)*7+floor*8),ped=new THREE.Mesh(new THREE.CylinderGeometry(1,1.15,.7,12),mat(0x444b57,.42,.45));ped.position.set(x,.35,1);world.add(ped);shopItems.push({x,z:1,w,cost,bought:false,ped})}shopItems.push({x:0,z:8,heal:true,cost:45+floor*7,bought:false})}
function weaponHTML(w){const r=RARITY[w.rarity];return `<span class="rarity" style="color:${r.color}">${r.label||w.rarity}</span><h3>${w.name}</h3><b>${w.type}</b><p>${w.desc}</p><small>${w.kind==='melee'?`DMG ${w.damage} · RANGE ${w.range} · ${w.rate}/s`:`DMG ${w.damage} · ${w.rate}/s · MAG ${w.mag??'-'} · RANGE ${w.range}`}</small>`}
function openChest(c){if(c.opened)return;c.opened=true;world.remove(c.mesh);releaseMouse();const opts=[pick(WEAPONS),pick(WEAPONS),pick(WEAPONS)];showChoices('Cache',opts.map(w=>({label:weaponHTML(w),action:()=>{replaceWeapon(w.id);closeModal()}})),true)}
function replaceWeapon(id){player.slots[player.slot]={id,ammo:wmap[id].mag??0,reload:0,cd:0};refreshHeldWeapon()}
function showChoices(title,items,skip=false){releaseMouse();modal.classList.add('show');modal.innerHTML=`<div class="card"><h2>${title}</h2><div class="grid">${items.map((it,i)=>`<button class="choice" data-i="${i}">${it.label}</button>`).join('')}${skip?'<button class="choice" data-skip><h3>Skip</h3></button>':''}</div></div>`;modal.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>items[+b.dataset.i].action());modal.querySelector('[data-skip]')?.addEventListener('click',()=>closeModal())}
function closeModal(relock=true){modal.classList.remove('show');if(relock)setTimeout(grabMouse,0)}
function interact(){for(const c of chests)if(!c.opened&&c.mesh.position.distanceTo(player.mesh.position)<3)return openChest(c);if(isShop){for(const it of shopItems){const d=Math.hypot(player.mesh.position.x-it.x,player.mesh.position.z-it.z);if(d<2.5&&!it.bought){if(player.coins<it.cost)return notice('Yetersiz kredi');player.coins-=it.cost;it.bought=true;if(it.heal)player.hp=Math.min(player.maxHp,player.hp+90);else replaceWeapon(it.w.id);return}}}if(roomClear&&player.mesh.position.z<-mapHalf+3)nextRoom()}
function nextRoom(){room++;if(room>=20){floor++;room=0;player.hp=Math.min(player.maxHp,player.hp+player.maxHp*.35)}buildRoom()}
function reload(){const s=player.slots[player.slot],w=currentWeapon();if(w.kind==='melee'||w.kind==='orbital'||s.reload>0)return;s.reload=w.reload}
function findNearestEnemy(max=999){let best=null,bd=max;for(const e of enemies)if(!e.dead){const d=e.mesh.position.distanceTo(player.mesh.position);if(d<bd){bd=d;best=e}}return best}
function cameraForward(){return new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(-pitch),Math.cos(yaw)*Math.cos(pitch)).normalize()}
function aimDirection(w){const origin=player.mesh.position.clone().add(new THREE.Vector3(.38,1.45,0));if(mouse.right){const ndc=new THREE.Vector3(.12,0.02,.5).unproject(camera),dir=ndc.sub(camera.position).normalize();return dir}return cameraForward()}
function fire(){const s=player.slots[player.slot],w=currentWeapon();if(s.cd>0||s.reload>0)return;s.cd=1/(w.rate*player.attackSpeed);if(w.kind==='melee')return melee(w);if(w.kind==='orbital')return spawnOrbital(w);if(s.ammo<=0)return reload();s.ammo--;const dir=aimDirection(w),origin=player.mesh.position.clone().add(new THREE.Vector3(.5,1.48,0)).addScaledVector(dir,.7);if(w.kind==='beam')return beamShot(origin,dir,w);for(let i=0;i<(w.pellets||1);i++){const d=dir.clone();if(w.spread){d.x+=rand(-w.spread,w.spread);d.y+=rand(-w.spread*.3,w.spread*.3);d.z+=rand(-w.spread,w.spread);d.normalize()}spawnBullet(origin,d,w)}}
function spawnBullet(origin,dir,w){const m=new THREE.Mesh(new THREE.SphereGeometry(w.kind==='grenade'?.18:.09,7,5),new THREE.MeshBasicMaterial({color:RARITY[w.rarity]?.color||0xffffff}));m.position.copy(origin);bulletGroup.add(m);bullets.push({mesh:m,vel:dir.clone().multiplyScalar(w.speed),life:(w.range||60)/Math.max(1,w.speed),w,damage:w.damage*player.damage,pierce:w.pierce||0})}
function beamShot(origin,dir,w){let nearest=null,nd=w.range;for(const e of enemies)if(!e.dead){const to=e.mesh.position.clone().add(new THREE.Vector3(0,1,0)).sub(origin),proj=to.dot(dir);if(proj>0&&proj<nd&&to.clone().sub(dir.clone().multiplyScalar(proj)).length()<e.r+.7){nearest=e;nd=proj}}if(nearest)hitEnemy(nearest,w.damage*player.damage*(nearest.boss?player.bossDamage:1))}
function spawnOrbital(w){for(let i=0;i<3;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(.18,7,5),new THREE.MeshBasicMaterial({color:RARITY[w.rarity]?.color||0xffffff}));bulletGroup.add(m);orbitals.push({mesh:m,angle:i*Math.PI*2/3,life:7,damage:w.damage})}}
function melee(w){const forward=new THREE.Vector3(Math.sin(player.mesh.rotation.y),0,Math.cos(player.mesh.rotation.y)).normalize(),origin=player.mesh.position.clone();const range=(w.range||3)*1.4,maxAngle=(w.arc||1.8)/2+.25;for(const e of enemies)if(!e.dead){const flat=e.mesh.position.clone().sub(origin);flat.y=0;const dist=flat.length();if(dist<=range+e.r&&Math.acos(clamp(flat.normalize().dot(forward),-1,1))<=maxAngle)hitEnemy(e,w.damage*player.damage*player.melee*(e.boss?player.bossDamage:1))}}
function hitEnemy(e,d){e.hp-=d;if(e.hp<=0&&!e.dead){e.dead=true;const pos=e.mesh.position.clone();enemyGroup.remove(e.mesh);player.xp+=e.xp||45;spawnCoin(pos,Math.max(3,Math.round((e.xp||40)/9)));player.hp=Math.min(player.maxHp,player.hp+player.killHeal);checkLevel()}}
function spawnCoin(pos,v){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(.16,0),new THREE.MeshBasicMaterial({color:0xffd25a}));m.position.copy(pos).add(new THREE.Vector3(0,.4,0));pickupGroup.add(m);pickups.push({mesh:m,v})}
function checkLevel(){while(player.xp>=player.nextXp){player.xp-=player.nextXp;player.level++;player.nextXp=Math.floor(player.nextXp*1.22+25);const opts=[...UPGRADES].sort(()=>Math.random()-.5).slice(0,3);showChoices(`Level ${player.level}`,opts.map(u=>({label:`<h3>${u.name}</h3><p>${u.desc}</p>`,action:()=>{u.apply(player);closeModal()}})))}}
function collidesWalls(p,r=.6){return walls.some(w=>Math.abs(p.x-w.x)<w.w/2+r&&Math.abs(p.z-w.z)<w.d/2+r)}function resolveWall(p,w,r){if(Math.abs(p.x-w.x)<w.w/2+r&&Math.abs(p.z-w.z)<w.d/2+r){const dx=w.w/2+r-Math.abs(p.x-w.x),dz=w.d/2+r-Math.abs(p.z-w.z);if(dx<dz)p.x+=Math.sign(p.x-w.x||1)*dx;else p.z+=Math.sign(p.z-w.z||1)*dz}}function segmentHitsWall(a,b,r=.08){const dist=a.distanceTo(b),steps=Math.max(2,Math.ceil(dist/.8));for(const w of walls)for(let i=1;i<=steps;i++){const p=tmpA.copy(a).lerp(b,i/steps);if(Math.abs(p.x-w.x)<w.w/2+r&&Math.abs(p.z-w.z)<w.d/2+r&&p.y<w.h+.3)return true}return false}
function movePlayer(dt){const f=new THREE.Vector3(Math.sin(yaw),0,Math.cos(yaw)),r=new THREE.Vector3(-f.z,0,f.x),dir=new THREE.Vector3();if(keys.KeyW)dir.add(f);if(keys.KeyS)dir.sub(f);if(keys.KeyD)dir.add(r);if(keys.KeyA)dir.sub(r);if(dir.lengthSq())dir.normalize();if(keys.ShiftLeft&&player.dash<=0){player.dash=player.dashMax;player.ifr=.2;dir.multiplyScalar(2.5)}player.dash=Math.max(0,player.dash-dt);player.mesh.position.addScaledVector(dir,player.speed*dt);player.mesh.position.x=clamp(player.mesh.position.x,-mapHalf+1.5,mapHalf-1.5);player.mesh.position.z=clamp(player.mesh.position.z,-mapHalf+1.5,mapHalf-1.5);for(const w of walls)resolveWall(player.mesh.position,w,.62);if(keys.Space&&player.onGround){player.yVel=8.7;player.onGround=false}player.yVel-=21*dt;player.mesh.position.y+=player.yVel*dt;if(player.mesh.position.y<=0){player.mesh.position.y=0;player.yVel=0;player.onGround=true}if(mouse.right)player.mesh.rotation.y=yaw;else if(dir.lengthSq())player.mesh.rotation.y=Math.atan2(dir.x,dir.z)}
function updateCamera(dt){if(mouse.right&&lockedTarget&&!lockedTarget.dead){const v=lockedTarget.mesh.position.clone().sub(player.mesh.position);yaw=Math.atan2(v.x,v.z);pitch=clamp(-Math.atan2(v.y+1,v.length()),-.42,.08)}const target=player.mesh.position.clone().add(new THREE.Vector3(0,1.15,0)),dist=mouse.right?5.9:9.6,up=mouse.right?3.35:4.2;const back=new THREE.Vector3(-Math.sin(yaw)*dist,up,-Math.cos(yaw)*dist),right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw));let desired=target.clone().add(back);if(mouse.right)desired.addScaledVector(right,.95);let safe=desired.clone();if(segmentHitsWall(target,desired,.2)){for(let t=.9;t>.18;t-=.08){const p=target.clone().lerp(desired,t);if(!segmentHitsWall(target,p,.18)){safe=p;break}}}camera.position.lerp(safe,1-Math.pow(.0007,dt));const look=target.clone().add(cameraForward().multiplyScalar(18));if(mouse.right)look.addScaledVector(right,-.55);camera.lookAt(look)}
function enemyShoot(e,dir,speed=12,count=1,spread=.12){for(let i=0;i<count;i++){const d=dir.clone();if(count>1){const a=(i-(count-1)/2)*spread,c=Math.cos(a),s=Math.sin(a),x=d.x*c-d.z*s,z=d.x*s+d.z*c;d.x=x;d.z=z}const m=new THREE.Mesh(new THREE.SphereGeometry(.13,7,5),new THREE.MeshBasicMaterial({color:e.color||0xff5a75}));m.position.copy(e.mesh.position).add(new THREE.Vector3(0,1.1,0));bulletGroup.add(m);enemyBullets.push({mesh:m,vel:d.normalize().multiplyScalar(speed),life:6,damage:e.damage||24})}}
function ring(e,n=14,s=9,o=0){for(let i=0;i<n;i++){const a=o+i*Math.PI*2/n;enemyShoot(e,new THREE.Vector3(Math.sin(a),0,Math.cos(a)),s)}}
function updateEnemies(dt){for(const e of enemies)if(!e.dead){e.t+=dt;e.cd-=dt;const to=player.mesh.position.clone().sub(e.mesh.position),dist=to.length(),dir=to.normalize(),spd=e.speed*Math.min(1.7,1+.08*floor),old=e.mesh.position.clone();if(e.boss)bossAI(e,dir,dt);else if(e.ai==='chase')e.mesh.position.addScaledVector(dir,spd*dt);else if(e.ai==='orbit'){const side=new THREE.Vector3(-dir.z,0,dir.x);e.mesh.position.addScaledVector(side,spd*dt);if(e.cd<=0){enemyShoot(e,dir,13);e.cd=1.1/difficulty}}else if(e.ai==='shooter'||e.ai==='sniper'){if(dist>12)e.mesh.position.addScaledVector(dir,spd*.5*dt);if(e.cd<=0){enemyShoot(e,dir,e.ai==='sniper'?19:13);e.cd=(e.ai==='sniper'?1.8:1)/Math.min(2,difficulty)}}else if(e.ai==='radial'&&e.cd<=0){ring(e,12+floor,9+floor*.25,e.t);e.cd=1.65/Math.min(2,difficulty)}else if(e.ai==='charge'){if(e.cd<=0){e.charge=.55;e.cd=2.1}if(e.charge>0){e.mesh.position.addScaledVector(dir,spd*3.2*dt);e.charge-=dt}}else if(e.ai==='spiral'&&e.cd<=0){for(let i=0;i<5;i++){const a=e.t+i*Math.PI*2/5;enemyShoot(e,new THREE.Vector3(Math.sin(a),0,Math.cos(a)),10)}e.cd=.34/Math.min(2,difficulty)}else if(e.ai==='rings'&&e.cd<=0){ring(e,18,9,e.t);e.cd=1.55/Math.min(2,difficulty)}else if(e.ai==='burst'&&e.cd<=0){enemyShoot(e,dir,14,5,.11);e.cd=.95/Math.min(2,difficulty)}else if(e.ai==='blink'&&e.cd<=0){const np=player.mesh.position.clone().add(new THREE.Vector3(rand(-9,9),0,rand(-9,9)));if(!collidesWalls(np,e.r))e.mesh.position.copy(np);e.cd=1.9}else if(e.ai==='satellite'&&e.cd<=0){ring(e,8,8,e.t);enemyShoot(e,dir,14);e.cd=.9/Math.min(2,difficulty)}else if(e.ai==='fan'&&e.cd<=0){enemyShoot(e,dir,13,7,.22);e.cd=1.1/Math.min(2,difficulty)};for(const w of walls)resolveWall(e.mesh.position,w,e.r*.7);if(segmentHitsWall(old,e.mesh.position,e.r*.2))e.mesh.position.copy(old);if(dist<e.r+.7)hurtPlayer((e.damage||24)*dt*1.8);e.mesh.rotation.y=Math.atan2(dir.x,dir.z)}}
function bossAI(e,dir,dt){const phase=1+Math.floor((1-e.hp/e.maxHp)*3);if(e.cd<=0){ring(e,16+phase*4,10+phase,e.t);enemyShoot(e,dir,16,3+phase*2,.11);e.cd=Math.max(.6,1.65-phase*.18)}e.mesh.position.addScaledVector(new THREE.Vector3(-dir.z,0,dir.x),1.4*dt);for(const w of walls)resolveWall(e.mesh.position,w,1.2)}
function updateBullets(dt){for(const b of bullets){const old=b.mesh.position.clone();if(b.w.kind==='homing'){const e=findNearestFrom(b.mesh.position,45);if(e){const desired=e.mesh.position.clone().add(new THREE.Vector3(0,1,0)).sub(b.mesh.position).normalize().multiplyScalar(b.w.speed);b.vel.lerp(desired,clamp(b.w.turn*dt,0,1))}}b.mesh.position.addScaledVector(b.vel,dt);b.life-=dt;if(segmentHitsWall(old,b.mesh.position,.1)){b.life=0;continue}for(const e of enemies)if(!e.dead&&b.mesh.position.distanceTo(e.mesh.position.clone().add(new THREE.Vector3(0,1,0)))<e.r+.32){hitEnemy(e,b.damage*(e.boss?player.bossDamage:1));if(b.pierce-->0){}else{b.life=0;break}}}for(const b of enemyBullets){const old=b.mesh.position.clone();b.mesh.position.addScaledVector(b.vel,dt);b.life-=dt;if(segmentHitsWall(old,b.mesh.position,.11)){b.life=0;continue}if(b.mesh.position.distanceTo(player.mesh.position.clone().add(new THREE.Vector3(0,1,0)))<.68){hurtPlayer(b.damage);b.life=0}}for(const o of orbitals){o.angle+=dt*3.6;o.life-=dt;o.mesh.position.copy(player.mesh.position).add(new THREE.Vector3(Math.cos(o.angle)*2.35,1.35,Math.sin(o.angle)*2.35));for(const e of enemies)if(!e.dead&&o.mesh.position.distanceTo(e.mesh.position)<e.r+.4)hitEnemy(e,o.damage*dt*3.3)}bullets=bullets.filter(b=>{if(b.life<=0){bulletGroup.remove(b.mesh);return false}return true});enemyBullets=enemyBullets.filter(b=>{if(b.life<=0){bulletGroup.remove(b.mesh);return false}return true});orbitals=orbitals.filter(o=>{if(o.life<=0){bulletGroup.remove(o.mesh);return false}return true})}
function findNearestFrom(pos,max){let best=null,bd=max;for(const e of enemies)if(!e.dead){const d=e.mesh.position.distanceTo(pos);if(d<bd){bd=d;best=e}}return best}function hurtPlayer(d){if(player.ifr>0)return;player.hp-=d;player.ifr=.18;if(player.hp<=0)gameOver()}function gameOver(){releaseMouse();modal.classList.add('show');modal.innerHTML=`<div class="card death"><h1>SYSTEM FAILURE</h1><button id="restart" class="choice"><h3>RESTART</h3></button></div>`;$('#restart').onclick=()=>location.reload()}
function updatePickups(dt){for(const p of pickups){p.mesh.rotation.y+=dt*3;const to=player.mesh.position.clone().add(new THREE.Vector3(0,.5,0)).sub(p.mesh.position),d=to.length(),radius=7.5*player.pickup;if(d<radius)p.mesh.position.addScaledVector(to.normalize(),dt*(8+radius-d));if(d<.75){player.coins+=p.v;p.dead=true;pickupGroup.remove(p.mesh)}}pickups=pickups.filter(p=>!p.dead)}
function shopHint(){if(!isShop)return'';let best=null,bd=99;for(const it of shopItems)if(!it.bought){const d=Math.hypot(player.mesh.position.x-it.x,player.mesh.position.z-it.z);if(d<bd){bd=d;best=it}}if(!best||bd>4)return'';return best.heal?`<div class="hint"><b>MEDKIT</b><span>${best.cost} CR · E</span></div>`:`<div class="hint"><b style="color:${RARITY[best.w.rarity].color}">${best.w.name}</b><span>${best.w.type} · ${best.cost} CR · E</span></div>`}
function drawHud(){const w=currentWeapon(),s=player.slots[player.slot],meleeCd=w.kind==='melee'?clamp(1-s.cd*w.rate*player.attackSpeed,0,1):1;hud.innerHTML=`<div class="topbar"><div><b>DECK ${floor} · SECTOR ${sector} · ROOM ${room+1}</b></div><div class="credits">◈ ${player.coins} CR</div></div><div class="health"><span>HP ${Math.ceil(player.hp)}/${Math.ceil(player.maxHp)}</span><i style="width:${clamp(player.hp/player.maxHp*100,0,100)}%"></i></div><div class="reticle ${mouse.right?'locked':''}"></div><div class="slots">${player.slots.map((q,i)=>{const ww=wmap[q.id];return`<div class="slot ${i===player.slot?'active':''}"><small>${i+1}</small><b style="color:${RARITY[ww.rarity].color}">${ww.name}</b><span>${ww.type}</span></div>`}).join('')}</div><div class="weaponinfo"><b>${w.name}</b><span>${w.kind==='melee'?'MELEE':`${s.reload>0?'RELOADING':s.ammo+'/'+(w.mag||0)}`}</span>${w.kind==='melee'?`<em><i style="width:${meleeCd*100}%"></i></em>`:''}</div>${shopHint()}<div class="controls">WASD · LMB fire · RMB shoulder/lock · 1/2/3 · E · Space · Shift</div>`}
function notice(t,time=1.4){const n=document.createElement('div');n.className='notice';n.textContent=t;document.body.appendChild(n);setTimeout(()=>n.remove(),time*1000)}
function update(dt){if(!player||modal.classList.contains('show'))return;for(const s of player.slots){s.cd=Math.max(0,s.cd-dt);if(s.reload>0){s.reload-=dt;if(s.reload<=0)s.ammo=wmap[s.id].mag??0}}player.ifr=Math.max(0,player.ifr-dt);movePlayer(dt);if(mouse.left)fire();updateCamera(dt);updateBullets(dt);updateEnemies(dt);updatePickups(dt);if(!roomClear&&enemies.every(e=>e.dead)){roomClear=true;notice(isBoss?'BOSS DOWN':'ROOM CLEAR');if(!isBoss&&Math.random()<.32)spawnChest(rand(-8,8),rand(-1,9))}drawHud()}
function animate(){requestAnimationFrame(animate);const dt=Math.min(.033,clock.getDelta());update(dt);renderer.render(scene,camera)}
init();